'use strict';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
Object.defineProperty(exports, '__esModule', { value: true });
exports.Status = exports.ReportFormat = void 0;
var ReportFormat;
(function (ReportFormat) {
  ReportFormat['CTRF'] = 'CTRF';
})(ReportFormat || (exports.ReportFormat = ReportFormat = {}));
var Status;
(function (Status) {
  Status['passed'] = 'passed';
  Status['failed'] = 'failed';
  Status['skipped'] = 'skipped';
  Status['pending'] = 'pending';
  Status['other'] = 'other';
})(Status || (exports.Status = Status = {}));
