{{- if .Values.database.enabled }}
{{- if not .Values.database.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaledtest.fullname" . }}-postgresql
  labels:
    {{- include "scaledtest.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.database.auth.password | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
{{- end }}
