// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MichielDean/ScaledTest/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterManager is an autogenerated mock type for the ClusterManager type
type MockClusterManager struct {
	mock.Mock
}

type MockClusterManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterManager) EXPECT() *MockClusterManager_Expecter {
	return &MockClusterManager_Expecter{mock: &_m.Mock}
}

// CreateCluster provides a mock function with given fields: ctx, cluster, credentials
func (_m *MockClusterManager) CreateCluster(ctx context.Context, cluster *models.K8sCluster, credentials *models.K8sClusterCredentials) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, cluster, credentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateCluster")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) (*models.K8sCluster, error)); ok {
		return rf(ctx, cluster, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) *models.K8sCluster); ok {
		r0 = rf(ctx, cluster, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) error); ok {
		r1 = rf(ctx, cluster, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_CreateCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCluster'
type MockClusterManager_CreateCluster_Call struct {
	*mock.Call
}

// CreateCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster *models.K8sCluster
//   - credentials *models.K8sClusterCredentials
func (_e *MockClusterManager_Expecter) CreateCluster(ctx interface{}, cluster interface{}, credentials interface{}) *MockClusterManager_CreateCluster_Call {
	return &MockClusterManager_CreateCluster_Call{Call: _e.mock.On("CreateCluster", ctx, cluster, credentials)}
}

func (_c *MockClusterManager_CreateCluster_Call) Run(run func(ctx context.Context, cluster *models.K8sCluster, credentials *models.K8sClusterCredentials)) *MockClusterManager_CreateCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.K8sCluster), args[2].(*models.K8sClusterCredentials))
	})
	return _c
}

func (_c *MockClusterManager_CreateCluster_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterManager_CreateCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_CreateCluster_Call) RunAndReturn(run func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) (*models.K8sCluster, error)) *MockClusterManager_CreateCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function with given fields: ctx, clusterID
func (_m *MockClusterManager) DeleteCluster(ctx context.Context, clusterID string) error {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterManager_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type MockClusterManager_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *MockClusterManager_Expecter) DeleteCluster(ctx interface{}, clusterID interface{}) *MockClusterManager_DeleteCluster_Call {
	return &MockClusterManager_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, clusterID)}
}

func (_c *MockClusterManager_DeleteCluster_Call) Run(run func(ctx context.Context, clusterID string)) *MockClusterManager_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_DeleteCluster_Call) Return(_a0 error) *MockClusterManager_DeleteCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterManager_DeleteCluster_Call) RunAndReturn(run func(context.Context, string) error) *MockClusterManager_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetCluster provides a mock function with given fields: ctx, clusterID
func (_m *MockClusterManager) GetCluster(ctx context.Context, clusterID string) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.K8sCluster, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.K8sCluster); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_GetCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCluster'
type MockClusterManager_GetCluster_Call struct {
	*mock.Call
}

// GetCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *MockClusterManager_Expecter) GetCluster(ctx interface{}, clusterID interface{}) *MockClusterManager_GetCluster_Call {
	return &MockClusterManager_GetCluster_Call{Call: _e.mock.On("GetCluster", ctx, clusterID)}
}

func (_c *MockClusterManager_GetCluster_Call) Run(run func(ctx context.Context, clusterID string)) *MockClusterManager_GetCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_GetCluster_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterManager_GetCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_GetCluster_Call) RunAndReturn(run func(context.Context, string) (*models.K8sCluster, error)) *MockClusterManager_GetCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterCredentials provides a mock function with given fields: ctx, clusterID
func (_m *MockClusterManager) GetClusterCredentials(ctx context.Context, clusterID string) (*models.K8sClusterCredentials, error) {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterCredentials")
	}

	var r0 *models.K8sClusterCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.K8sClusterCredentials, error)); ok {
		return rf(ctx, clusterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.K8sClusterCredentials); ok {
		r0 = rf(ctx, clusterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sClusterCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_GetClusterCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterCredentials'
type MockClusterManager_GetClusterCredentials_Call struct {
	*mock.Call
}

// GetClusterCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *MockClusterManager_Expecter) GetClusterCredentials(ctx interface{}, clusterID interface{}) *MockClusterManager_GetClusterCredentials_Call {
	return &MockClusterManager_GetClusterCredentials_Call{Call: _e.mock.On("GetClusterCredentials", ctx, clusterID)}
}

func (_c *MockClusterManager_GetClusterCredentials_Call) Run(run func(ctx context.Context, clusterID string)) *MockClusterManager_GetClusterCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_GetClusterCredentials_Call) Return(_a0 *models.K8sClusterCredentials, _a1 error) *MockClusterManager_GetClusterCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_GetClusterCredentials_Call) RunAndReturn(run func(context.Context, string) (*models.K8sClusterCredentials, error)) *MockClusterManager_GetClusterCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultCluster provides a mock function with given fields: ctx, projectID
func (_m *MockClusterManager) GetDefaultCluster(ctx context.Context, projectID string) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultCluster")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.K8sCluster, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.K8sCluster); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_GetDefaultCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultCluster'
type MockClusterManager_GetDefaultCluster_Call struct {
	*mock.Call
}

// GetDefaultCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockClusterManager_Expecter) GetDefaultCluster(ctx interface{}, projectID interface{}) *MockClusterManager_GetDefaultCluster_Call {
	return &MockClusterManager_GetDefaultCluster_Call{Call: _e.mock.On("GetDefaultCluster", ctx, projectID)}
}

func (_c *MockClusterManager_GetDefaultCluster_Call) Run(run func(ctx context.Context, projectID string)) *MockClusterManager_GetDefaultCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_GetDefaultCluster_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterManager_GetDefaultCluster_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_GetDefaultCluster_Call) RunAndReturn(run func(context.Context, string) (*models.K8sCluster, error)) *MockClusterManager_GetDefaultCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultClusterForEnvironment provides a mock function with given fields: ctx, projectID, environment
func (_m *MockClusterManager) GetDefaultClusterForEnvironment(ctx context.Context, projectID string, environment models.Environment) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID, environment)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultClusterForEnvironment")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) (*models.K8sCluster, error)); ok {
		return rf(ctx, projectID, environment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) *models.K8sCluster); ok {
		r0 = rf(ctx, projectID, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Environment) error); ok {
		r1 = rf(ctx, projectID, environment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_GetDefaultClusterForEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultClusterForEnvironment'
type MockClusterManager_GetDefaultClusterForEnvironment_Call struct {
	*mock.Call
}

// GetDefaultClusterForEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - environment models.Environment
func (_e *MockClusterManager_Expecter) GetDefaultClusterForEnvironment(ctx interface{}, projectID interface{}, environment interface{}) *MockClusterManager_GetDefaultClusterForEnvironment_Call {
	return &MockClusterManager_GetDefaultClusterForEnvironment_Call{Call: _e.mock.On("GetDefaultClusterForEnvironment", ctx, projectID, environment)}
}

func (_c *MockClusterManager_GetDefaultClusterForEnvironment_Call) Run(run func(ctx context.Context, projectID string, environment models.Environment)) *MockClusterManager_GetDefaultClusterForEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Environment))
	})
	return _c
}

func (_c *MockClusterManager_GetDefaultClusterForEnvironment_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterManager_GetDefaultClusterForEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_GetDefaultClusterForEnvironment_Call) RunAndReturn(run func(context.Context, string, models.Environment) (*models.K8sCluster, error)) *MockClusterManager_GetDefaultClusterForEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusters provides a mock function with given fields: ctx, projectID
func (_m *MockClusterManager) ListClusters(ctx context.Context, projectID string) ([]*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListClusters")
	}

	var r0 []*models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.K8sCluster, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.K8sCluster); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type MockClusterManager_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockClusterManager_Expecter) ListClusters(ctx interface{}, projectID interface{}) *MockClusterManager_ListClusters_Call {
	return &MockClusterManager_ListClusters_Call{Call: _e.mock.On("ListClusters", ctx, projectID)}
}

func (_c *MockClusterManager_ListClusters_Call) Run(run func(ctx context.Context, projectID string)) *MockClusterManager_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_ListClusters_Call) Return(_a0 []*models.K8sCluster, _a1 error) *MockClusterManager_ListClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_ListClusters_Call) RunAndReturn(run func(context.Context, string) ([]*models.K8sCluster, error)) *MockClusterManager_ListClusters_Call {
	_c.Call.Return(run)
	return _c
}

// ListClustersByEnvironment provides a mock function with given fields: ctx, projectID, environment
func (_m *MockClusterManager) ListClustersByEnvironment(ctx context.Context, projectID string, environment models.Environment) ([]*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID, environment)

	if len(ret) == 0 {
		panic("no return value specified for ListClustersByEnvironment")
	}

	var r0 []*models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) ([]*models.K8sCluster, error)); ok {
		return rf(ctx, projectID, environment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) []*models.K8sCluster); ok {
		r0 = rf(ctx, projectID, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Environment) error); ok {
		r1 = rf(ctx, projectID, environment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterManager_ListClustersByEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClustersByEnvironment'
type MockClusterManager_ListClustersByEnvironment_Call struct {
	*mock.Call
}

// ListClustersByEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - environment models.Environment
func (_e *MockClusterManager_Expecter) ListClustersByEnvironment(ctx interface{}, projectID interface{}, environment interface{}) *MockClusterManager_ListClustersByEnvironment_Call {
	return &MockClusterManager_ListClustersByEnvironment_Call{Call: _e.mock.On("ListClustersByEnvironment", ctx, projectID, environment)}
}

func (_c *MockClusterManager_ListClustersByEnvironment_Call) Run(run func(ctx context.Context, projectID string, environment models.Environment)) *MockClusterManager_ListClustersByEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Environment))
	})
	return _c
}

func (_c *MockClusterManager_ListClustersByEnvironment_Call) Return(_a0 []*models.K8sCluster, _a1 error) *MockClusterManager_ListClustersByEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterManager_ListClustersByEnvironment_Call) RunAndReturn(run func(context.Context, string, models.Environment) ([]*models.K8sCluster, error)) *MockClusterManager_ListClustersByEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultCluster provides a mock function with given fields: ctx, clusterID
func (_m *MockClusterManager) SetDefaultCluster(ctx context.Context, clusterID string) error {
	ret := _m.Called(ctx, clusterID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterManager_SetDefaultCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultCluster'
type MockClusterManager_SetDefaultCluster_Call struct {
	*mock.Call
}

// SetDefaultCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
func (_e *MockClusterManager_Expecter) SetDefaultCluster(ctx interface{}, clusterID interface{}) *MockClusterManager_SetDefaultCluster_Call {
	return &MockClusterManager_SetDefaultCluster_Call{Call: _e.mock.On("SetDefaultCluster", ctx, clusterID)}
}

func (_c *MockClusterManager_SetDefaultCluster_Call) Run(run func(ctx context.Context, clusterID string)) *MockClusterManager_SetDefaultCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterManager_SetDefaultCluster_Call) Return(_a0 error) *MockClusterManager_SetDefaultCluster_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterManager_SetDefaultCluster_Call) RunAndReturn(run func(context.Context, string) error) *MockClusterManager_SetDefaultCluster_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterStatus provides a mock function with given fields: ctx, clusterID, status, errorMsg
func (_m *MockClusterManager) UpdateClusterStatus(ctx context.Context, clusterID string, status string, errorMsg *string) error {
	ret := _m.Called(ctx, clusterID, status, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = rf(ctx, clusterID, status, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterManager_UpdateClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterStatus'
type MockClusterManager_UpdateClusterStatus_Call struct {
	*mock.Call
}

// UpdateClusterStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - status string
//   - errorMsg *string
func (_e *MockClusterManager_Expecter) UpdateClusterStatus(ctx interface{}, clusterID interface{}, status interface{}, errorMsg interface{}) *MockClusterManager_UpdateClusterStatus_Call {
	return &MockClusterManager_UpdateClusterStatus_Call{Call: _e.mock.On("UpdateClusterStatus", ctx, clusterID, status, errorMsg)}
}

func (_c *MockClusterManager_UpdateClusterStatus_Call) Run(run func(ctx context.Context, clusterID string, status string, errorMsg *string)) *MockClusterManager_UpdateClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockClusterManager_UpdateClusterStatus_Call) Return(_a0 error) *MockClusterManager_UpdateClusterStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterManager_UpdateClusterStatus_Call) RunAndReturn(run func(context.Context, string, string, *string) error) *MockClusterManager_UpdateClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRunnerConfig provides a mock function with given fields: ctx, clusterID, config
func (_m *MockClusterManager) UpdateRunnerConfig(ctx context.Context, clusterID string, config models.RunnerConfig) error {
	ret := _m.Called(ctx, clusterID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunnerConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.RunnerConfig) error); ok {
		r0 = rf(ctx, clusterID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterManager_UpdateRunnerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRunnerConfig'
type MockClusterManager_UpdateRunnerConfig_Call struct {
	*mock.Call
}

// UpdateRunnerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - config models.RunnerConfig
func (_e *MockClusterManager_Expecter) UpdateRunnerConfig(ctx interface{}, clusterID interface{}, config interface{}) *MockClusterManager_UpdateRunnerConfig_Call {
	return &MockClusterManager_UpdateRunnerConfig_Call{Call: _e.mock.On("UpdateRunnerConfig", ctx, clusterID, config)}
}

func (_c *MockClusterManager_UpdateRunnerConfig_Call) Run(run func(ctx context.Context, clusterID string, config models.RunnerConfig)) *MockClusterManager_UpdateRunnerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.RunnerConfig))
	})
	return _c
}

func (_c *MockClusterManager_UpdateRunnerConfig_Call) Return(_a0 error) *MockClusterManager_UpdateRunnerConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterManager_UpdateRunnerConfig_Call) RunAndReturn(run func(context.Context, string, models.RunnerConfig) error) *MockClusterManager_UpdateRunnerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSutConfig provides a mock function with given fields: ctx, clusterID, config
func (_m *MockClusterManager) UpdateSutConfig(ctx context.Context, clusterID string, config *models.SutConfig) error {
	ret := _m.Called(ctx, clusterID, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSutConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SutConfig) error); ok {
		r0 = rf(ctx, clusterID, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterManager_UpdateSutConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSutConfig'
type MockClusterManager_UpdateSutConfig_Call struct {
	*mock.Call
}

// UpdateSutConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterID string
//   - config *models.SutConfig
func (_e *MockClusterManager_Expecter) UpdateSutConfig(ctx interface{}, clusterID interface{}, config interface{}) *MockClusterManager_UpdateSutConfig_Call {
	return &MockClusterManager_UpdateSutConfig_Call{Call: _e.mock.On("UpdateSutConfig", ctx, clusterID, config)}
}

func (_c *MockClusterManager_UpdateSutConfig_Call) Run(run func(ctx context.Context, clusterID string, config *models.SutConfig)) *MockClusterManager_UpdateSutConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.SutConfig))
	})
	return _c
}

func (_c *MockClusterManager_UpdateSutConfig_Call) Return(_a0 error) *MockClusterManager_UpdateSutConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterManager_UpdateSutConfig_Call) RunAndReturn(run func(context.Context, string, *models.SutConfig) error) *MockClusterManager_UpdateSutConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterManager creates a new instance of MockClusterManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterManager {
	mock := &MockClusterManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
