// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MichielDean/ScaledTest/backend/internal/models"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/MichielDean/ScaledTest/backend/internal/repository"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetProfileByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetProfileByID(ctx context.Context, id string) (*models.Profile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByID")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Profile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Profile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetProfileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileByID'
type MockUserRepository_GetProfileByID_Call struct {
	*mock.Call
}

// GetProfileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetProfileByID(ctx interface{}, id interface{}) *MockUserRepository_GetProfileByID_Call {
	return &MockUserRepository_GetProfileByID_Call{Call: _e.mock.On("GetProfileByID", ctx, id)}
}

func (_c *MockUserRepository_GetProfileByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetProfileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetProfileByID_Call) Return(_a0 *models.Profile, _a1 error) *MockUserRepository_GetProfileByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetProfileByID_Call) RunAndReturn(run func(context.Context, string) (*models.Profile, error)) *MockUserRepository_GetProfileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithRole provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetUserWithRole(ctx context.Context, id string) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithRole")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithRole'
type MockUserRepository_GetUserWithRole_Call struct {
	*mock.Call
}

// GetUserWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetUserWithRole(ctx interface{}, id interface{}) *MockUserRepository_GetUserWithRole_Call {
	return &MockUserRepository_GetUserWithRole_Call{Call: _e.mock.On("GetUserWithRole", ctx, id)}
}

func (_c *MockUserRepository_GetUserWithRole_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetUserWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserWithRole_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetUserWithRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserWithRole_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_GetUserWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, opts
func (_m *MockUserRepository) ListUsers(ctx context.Context, opts repository.ListUsersOptions) ([]*models.User, int32, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*models.User
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListUsersOptions) ([]*models.User, int32, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListUsersOptions) []*models.User); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListUsersOptions) int32); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ListUsersOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - opts repository.ListUsersOptions
func (_e *MockUserRepository_Expecter) ListUsers(ctx interface{}, opts interface{}) *MockUserRepository_ListUsers_Call {
	return &MockUserRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, opts)}
}

func (_c *MockUserRepository_ListUsers_Call) Run(run func(ctx context.Context, opts repository.ListUsersOptions)) *MockUserRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ListUsersOptions))
	})
	return _c
}

func (_c *MockUserRepository_ListUsers_Call) Return(_a0 []*models.User, _a1 int32, _a2 error) *MockUserRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserRepository_ListUsers_Call) RunAndReturn(run func(context.Context, repository.ListUsersOptions) ([]*models.User, int32, error)) *MockUserRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, profile
func (_m *MockUserRepository) UpdateProfile(ctx context.Context, profile *models.Profile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *models.Profile
func (_e *MockUserRepository_Expecter) UpdateProfile(ctx interface{}, profile interface{}) *MockUserRepository_UpdateProfile_Call {
	return &MockUserRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profile)}
}

func (_c *MockUserRepository_UpdateProfile_Call) Run(run func(ctx context.Context, profile *models.Profile)) *MockUserRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Profile))
	})
	return _c
}

func (_c *MockUserRepository_UpdateProfile_Call) Return(_a0 error) *MockUserRepository_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateProfile_Call) RunAndReturn(run func(context.Context, *models.Profile) error) *MockUserRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
