// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MichielDean/ScaledTest/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectManager is an autogenerated mock type for the ProjectManager type
type MockProjectManager struct {
	mock.Mock
}

type MockProjectManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectManager) EXPECT() *MockProjectManager_Expecter {
	return &MockProjectManager_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings
func (_m *MockProjectManager) CreateProject(ctx context.Context, name string, description *string, gitRepositoryURL *string, createdBy string, organizationID *string, settings map[string]string) (*models.Project, error) {
	ret := _m.Called(ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, string, *string, map[string]string) (*models.Project, error)); ok {
		return rf(ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, string, *string, map[string]string) *models.Project); ok {
		r0 = rf(ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, string, *string, map[string]string) error); ok {
		r1 = rf(ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectManager_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockProjectManager_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - gitRepositoryURL *string
//   - createdBy string
//   - organizationID *string
//   - settings map[string]string
func (_e *MockProjectManager_Expecter) CreateProject(ctx interface{}, name interface{}, description interface{}, gitRepositoryURL interface{}, createdBy interface{}, organizationID interface{}, settings interface{}) *MockProjectManager_CreateProject_Call {
	return &MockProjectManager_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, name, description, gitRepositoryURL, createdBy, organizationID, settings)}
}

func (_c *MockProjectManager_CreateProject_Call) Run(run func(ctx context.Context, name string, description *string, gitRepositoryURL *string, createdBy string, organizationID *string, settings map[string]string)) *MockProjectManager_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(string), args[5].(*string), args[6].(map[string]string))
	})
	return _c
}

func (_c *MockProjectManager_CreateProject_Call) Return(_a0 *models.Project, _a1 error) *MockProjectManager_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectManager_CreateProject_Call) RunAndReturn(run func(context.Context, string, *string, *string, string, *string, map[string]string) (*models.Project, error)) *MockProjectManager_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, projectID
func (_m *MockProjectManager) DeleteProject(ctx context.Context, projectID string) error {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, projectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectManager_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockProjectManager_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockProjectManager_Expecter) DeleteProject(ctx interface{}, projectID interface{}) *MockProjectManager_DeleteProject_Call {
	return &MockProjectManager_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, projectID)}
}

func (_c *MockProjectManager_DeleteProject_Call) Run(run func(ctx context.Context, projectID string)) *MockProjectManager_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectManager_DeleteProject_Call) Return(_a0 error) *MockProjectManager_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectManager_DeleteProject_Call) RunAndReturn(run func(context.Context, string) error) *MockProjectManager_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, projectID
func (_m *MockProjectManager) GetProject(ctx context.Context, projectID string) (*models.Project, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Project, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Project); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectManager_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockProjectManager_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockProjectManager_Expecter) GetProject(ctx interface{}, projectID interface{}) *MockProjectManager_GetProject_Call {
	return &MockProjectManager_GetProject_Call{Call: _e.mock.On("GetProject", ctx, projectID)}
}

func (_c *MockProjectManager_GetProject_Call) Run(run func(ctx context.Context, projectID string)) *MockProjectManager_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectManager_GetProject_Call) Return(_a0 *models.Project, _a1 error) *MockProjectManager_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectManager_GetProject_Call) RunAndReturn(run func(context.Context, string) (*models.Project, error)) *MockProjectManager_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockProjectManager) ListProjects(ctx context.Context, userID string, page int32, pageSize int32) ([]*models.Project, int32, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 []*models.Project
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]*models.Project, int32, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) []*models.Project); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) int32); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, int32) error); ok {
		r2 = rf(ctx, userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProjectManager_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockProjectManager_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int32
//   - pageSize int32
func (_e *MockProjectManager_Expecter) ListProjects(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockProjectManager_ListProjects_Call {
	return &MockProjectManager_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx, userID, page, pageSize)}
}

func (_c *MockProjectManager_ListProjects_Call) Run(run func(ctx context.Context, userID string, page int32, pageSize int32)) *MockProjectManager_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockProjectManager_ListProjects_Call) Return(_a0 []*models.Project, _a1 int32, _a2 error) *MockProjectManager_ListProjects_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProjectManager_ListProjects_Call) RunAndReturn(run func(context.Context, string, int32, int32) ([]*models.Project, int32, error)) *MockProjectManager_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, projectID, name, description, gitRepositoryURL, settings
func (_m *MockProjectManager) UpdateProject(ctx context.Context, projectID string, name *string, description *string, gitRepositoryURL *string, settings map[string]string) (*models.Project, error) {
	ret := _m.Called(ctx, projectID, name, description, gitRepositoryURL, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, *string, map[string]string) (*models.Project, error)); ok {
		return rf(ctx, projectID, name, description, gitRepositoryURL, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, *string, map[string]string) *models.Project); ok {
		r0 = rf(ctx, projectID, name, description, gitRepositoryURL, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, *string, map[string]string) error); ok {
		r1 = rf(ctx, projectID, name, description, gitRepositoryURL, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectManager_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectManager_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - name *string
//   - description *string
//   - gitRepositoryURL *string
//   - settings map[string]string
func (_e *MockProjectManager_Expecter) UpdateProject(ctx interface{}, projectID interface{}, name interface{}, description interface{}, gitRepositoryURL interface{}, settings interface{}) *MockProjectManager_UpdateProject_Call {
	return &MockProjectManager_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, projectID, name, description, gitRepositoryURL, settings)}
}

func (_c *MockProjectManager_UpdateProject_Call) Run(run func(ctx context.Context, projectID string, name *string, description *string, gitRepositoryURL *string, settings map[string]string)) *MockProjectManager_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(*string), args[5].(map[string]string))
	})
	return _c
}

func (_c *MockProjectManager_UpdateProject_Call) Return(_a0 *models.Project, _a1 error) *MockProjectManager_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectManager_UpdateProject_Call) RunAndReturn(run func(context.Context, string, *string, *string, *string, map[string]string) (*models.Project, error)) *MockProjectManager_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectManager creates a new instance of MockProjectManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectManager {
	mock := &MockProjectManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
