// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/MichielDean/ScaledTest/backend/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistryManager is an autogenerated mock type for the RegistryManager type
type MockRegistryManager struct {
	mock.Mock
}

type MockRegistryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryManager) EXPECT() *MockRegistryManager_Expecter {
	return &MockRegistryManager_Expecter{mock: &_m.Mock}
}

// AddContainerRegistry provides a mock function with given fields: ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy
func (_m *MockRegistryManager) AddContainerRegistry(ctx context.Context, projectID *string, name string, registryURL string, registryType string, username *string, credentials *string, authType string, createdBy string) (*services.ContainerRegistry, error) {
	ret := _m.Called(ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for AddContainerRegistry")
	}

	var r0 *services.ContainerRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, string, string, string, *string, *string, string, string) (*services.ContainerRegistry, error)); ok {
		return rf(ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, string, string, string, *string, *string, string, string) *services.ContainerRegistry); ok {
		r0 = rf(ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ContainerRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, string, string, string, *string, *string, string, string) error); ok {
		r1 = rf(ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryManager_AddContainerRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddContainerRegistry'
type MockRegistryManager_AddContainerRegistry_Call struct {
	*mock.Call
}

// AddContainerRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID *string
//   - name string
//   - registryURL string
//   - registryType string
//   - username *string
//   - credentials *string
//   - authType string
//   - createdBy string
func (_e *MockRegistryManager_Expecter) AddContainerRegistry(ctx interface{}, projectID interface{}, name interface{}, registryURL interface{}, registryType interface{}, username interface{}, credentials interface{}, authType interface{}, createdBy interface{}) *MockRegistryManager_AddContainerRegistry_Call {
	return &MockRegistryManager_AddContainerRegistry_Call{Call: _e.mock.On("AddContainerRegistry", ctx, projectID, name, registryURL, registryType, username, credentials, authType, createdBy)}
}

func (_c *MockRegistryManager_AddContainerRegistry_Call) Run(run func(ctx context.Context, projectID *string, name string, registryURL string, registryType string, username *string, credentials *string, authType string, createdBy string)) *MockRegistryManager_AddContainerRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string), args[6].(*string), args[7].(string), args[8].(string))
	})
	return _c
}

func (_c *MockRegistryManager_AddContainerRegistry_Call) Return(_a0 *services.ContainerRegistry, _a1 error) *MockRegistryManager_AddContainerRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryManager_AddContainerRegistry_Call) RunAndReturn(run func(context.Context, *string, string, string, string, *string, *string, string, string) (*services.ContainerRegistry, error)) *MockRegistryManager_AddContainerRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteContainerRegistry provides a mock function with given fields: ctx, registryID
func (_m *MockRegistryManager) DeleteContainerRegistry(ctx context.Context, registryID string) error {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContainerRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistryManager_DeleteContainerRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteContainerRegistry'
type MockRegistryManager_DeleteContainerRegistry_Call struct {
	*mock.Call
}

// DeleteContainerRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
func (_e *MockRegistryManager_Expecter) DeleteContainerRegistry(ctx interface{}, registryID interface{}) *MockRegistryManager_DeleteContainerRegistry_Call {
	return &MockRegistryManager_DeleteContainerRegistry_Call{Call: _e.mock.On("DeleteContainerRegistry", ctx, registryID)}
}

func (_c *MockRegistryManager_DeleteContainerRegistry_Call) Run(run func(ctx context.Context, registryID string)) *MockRegistryManager_DeleteContainerRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryManager_DeleteContainerRegistry_Call) Return(_a0 error) *MockRegistryManager_DeleteContainerRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistryManager_DeleteContainerRegistry_Call) RunAndReturn(run func(context.Context, string) error) *MockRegistryManager_DeleteContainerRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerRegistry provides a mock function with given fields: ctx, registryID
func (_m *MockRegistryManager) GetContainerRegistry(ctx context.Context, registryID string) (*services.ContainerRegistry, error) {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerRegistry")
	}

	var r0 *services.ContainerRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.ContainerRegistry, error)); ok {
		return rf(ctx, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.ContainerRegistry); ok {
		r0 = rf(ctx, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ContainerRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryManager_GetContainerRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerRegistry'
type MockRegistryManager_GetContainerRegistry_Call struct {
	*mock.Call
}

// GetContainerRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
func (_e *MockRegistryManager_Expecter) GetContainerRegistry(ctx interface{}, registryID interface{}) *MockRegistryManager_GetContainerRegistry_Call {
	return &MockRegistryManager_GetContainerRegistry_Call{Call: _e.mock.On("GetContainerRegistry", ctx, registryID)}
}

func (_c *MockRegistryManager_GetContainerRegistry_Call) Run(run func(ctx context.Context, registryID string)) *MockRegistryManager_GetContainerRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryManager_GetContainerRegistry_Call) Return(_a0 *services.ContainerRegistry, _a1 error) *MockRegistryManager_GetContainerRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryManager_GetContainerRegistry_Call) RunAndReturn(run func(context.Context, string) (*services.ContainerRegistry, error)) *MockRegistryManager_GetContainerRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegistryCredentials provides a mock function with given fields: ctx, registryID
func (_m *MockRegistryManager) GetRegistryCredentials(ctx context.Context, registryID string) (string, error) {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for GetRegistryCredentials")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, registryID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryManager_GetRegistryCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegistryCredentials'
type MockRegistryManager_GetRegistryCredentials_Call struct {
	*mock.Call
}

// GetRegistryCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
func (_e *MockRegistryManager_Expecter) GetRegistryCredentials(ctx interface{}, registryID interface{}) *MockRegistryManager_GetRegistryCredentials_Call {
	return &MockRegistryManager_GetRegistryCredentials_Call{Call: _e.mock.On("GetRegistryCredentials", ctx, registryID)}
}

func (_c *MockRegistryManager_GetRegistryCredentials_Call) Run(run func(ctx context.Context, registryID string)) *MockRegistryManager_GetRegistryCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryManager_GetRegistryCredentials_Call) Return(_a0 string, _a1 error) *MockRegistryManager_GetRegistryCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryManager_GetRegistryCredentials_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRegistryManager_GetRegistryCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainerRegistries provides a mock function with given fields: ctx, userID, projectID, page, pageSize
func (_m *MockRegistryManager) ListContainerRegistries(ctx context.Context, userID string, projectID *string, page int32, pageSize int32) ([]*services.ContainerRegistry, int32, error) {
	ret := _m.Called(ctx, userID, projectID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListContainerRegistries")
	}

	var r0 []*services.ContainerRegistry
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, int32, int32) ([]*services.ContainerRegistry, int32, error)); ok {
		return rf(ctx, userID, projectID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, int32, int32) []*services.ContainerRegistry); ok {
		r0 = rf(ctx, userID, projectID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.ContainerRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, int32, int32) int32); ok {
		r1 = rf(ctx, userID, projectID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *string, int32, int32) error); ok {
		r2 = rf(ctx, userID, projectID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRegistryManager_ListContainerRegistries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainerRegistries'
type MockRegistryManager_ListContainerRegistries_Call struct {
	*mock.Call
}

// ListContainerRegistries is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - projectID *string
//   - page int32
//   - pageSize int32
func (_e *MockRegistryManager_Expecter) ListContainerRegistries(ctx interface{}, userID interface{}, projectID interface{}, page interface{}, pageSize interface{}) *MockRegistryManager_ListContainerRegistries_Call {
	return &MockRegistryManager_ListContainerRegistries_Call{Call: _e.mock.On("ListContainerRegistries", ctx, userID, projectID, page, pageSize)}
}

func (_c *MockRegistryManager_ListContainerRegistries_Call) Run(run func(ctx context.Context, userID string, projectID *string, page int32, pageSize int32)) *MockRegistryManager_ListContainerRegistries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(int32), args[4].(int32))
	})
	return _c
}

func (_c *MockRegistryManager_ListContainerRegistries_Call) Return(_a0 []*services.ContainerRegistry, _a1 int32, _a2 error) *MockRegistryManager_ListContainerRegistries_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRegistryManager_ListContainerRegistries_Call) RunAndReturn(run func(context.Context, string, *string, int32, int32) ([]*services.ContainerRegistry, int32, error)) *MockRegistryManager_ListContainerRegistries_Call {
	_c.Call.Return(run)
	return _c
}

// SyncRegistryImages provides a mock function with given fields: ctx, registryID
func (_m *MockRegistryManager) SyncRegistryImages(ctx context.Context, registryID string) ([]*services.RegistryImage, error) {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for SyncRegistryImages")
	}

	var r0 []*services.RegistryImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*services.RegistryImage, error)); ok {
		return rf(ctx, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*services.RegistryImage); ok {
		r0 = rf(ctx, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.RegistryImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryManager_SyncRegistryImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncRegistryImages'
type MockRegistryManager_SyncRegistryImages_Call struct {
	*mock.Call
}

// SyncRegistryImages is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
func (_e *MockRegistryManager_Expecter) SyncRegistryImages(ctx interface{}, registryID interface{}) *MockRegistryManager_SyncRegistryImages_Call {
	return &MockRegistryManager_SyncRegistryImages_Call{Call: _e.mock.On("SyncRegistryImages", ctx, registryID)}
}

func (_c *MockRegistryManager_SyncRegistryImages_Call) Run(run func(ctx context.Context, registryID string)) *MockRegistryManager_SyncRegistryImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryManager_SyncRegistryImages_Call) Return(_a0 []*services.RegistryImage, _a1 error) *MockRegistryManager_SyncRegistryImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryManager_SyncRegistryImages_Call) RunAndReturn(run func(context.Context, string) ([]*services.RegistryImage, error)) *MockRegistryManager_SyncRegistryImages_Call {
	_c.Call.Return(run)
	return _c
}

// TestRegistryConnection provides a mock function with given fields: ctx, registryID
func (_m *MockRegistryManager) TestRegistryConnection(ctx context.Context, registryID string) (bool, string, error) {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for TestRegistryConnection")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, string, error)); ok {
		return rf(ctx, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, registryID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, registryID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, registryID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRegistryManager_TestRegistryConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestRegistryConnection'
type MockRegistryManager_TestRegistryConnection_Call struct {
	*mock.Call
}

// TestRegistryConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
func (_e *MockRegistryManager_Expecter) TestRegistryConnection(ctx interface{}, registryID interface{}) *MockRegistryManager_TestRegistryConnection_Call {
	return &MockRegistryManager_TestRegistryConnection_Call{Call: _e.mock.On("TestRegistryConnection", ctx, registryID)}
}

func (_c *MockRegistryManager_TestRegistryConnection_Call) Run(run func(ctx context.Context, registryID string)) *MockRegistryManager_TestRegistryConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryManager_TestRegistryConnection_Call) Return(_a0 bool, _a1 string, _a2 error) *MockRegistryManager_TestRegistryConnection_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRegistryManager_TestRegistryConnection_Call) RunAndReturn(run func(context.Context, string) (bool, string, error)) *MockRegistryManager_TestRegistryConnection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateContainerRegistry provides a mock function with given fields: ctx, registryID, name, username, credentials
func (_m *MockRegistryManager) UpdateContainerRegistry(ctx context.Context, registryID string, name *string, username *string, credentials *string) (*services.ContainerRegistry, error) {
	ret := _m.Called(ctx, registryID, name, username, credentials)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContainerRegistry")
	}

	var r0 *services.ContainerRegistry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, *string) (*services.ContainerRegistry, error)); ok {
		return rf(ctx, registryID, name, username, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, *string) *services.ContainerRegistry); ok {
		r0 = rf(ctx, registryID, name, username, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ContainerRegistry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, *string) error); ok {
		r1 = rf(ctx, registryID, name, username, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistryManager_UpdateContainerRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateContainerRegistry'
type MockRegistryManager_UpdateContainerRegistry_Call struct {
	*mock.Call
}

// UpdateContainerRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
//   - name *string
//   - username *string
//   - credentials *string
func (_e *MockRegistryManager_Expecter) UpdateContainerRegistry(ctx interface{}, registryID interface{}, name interface{}, username interface{}, credentials interface{}) *MockRegistryManager_UpdateContainerRegistry_Call {
	return &MockRegistryManager_UpdateContainerRegistry_Call{Call: _e.mock.On("UpdateContainerRegistry", ctx, registryID, name, username, credentials)}
}

func (_c *MockRegistryManager_UpdateContainerRegistry_Call) Run(run func(ctx context.Context, registryID string, name *string, username *string, credentials *string)) *MockRegistryManager_UpdateContainerRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockRegistryManager_UpdateContainerRegistry_Call) Return(_a0 *services.ContainerRegistry, _a1 error) *MockRegistryManager_UpdateContainerRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistryManager_UpdateContainerRegistry_Call) RunAndReturn(run func(context.Context, string, *string, *string, *string) (*services.ContainerRegistry, error)) *MockRegistryManager_UpdateContainerRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistryManager creates a new instance of MockRegistryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryManager {
	mock := &MockRegistryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
