// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MichielDean/ScaledTest/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockClusterRepository is an autogenerated mock type for the ClusterRepository type
type MockClusterRepository struct {
	mock.Mock
}

type MockClusterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClusterRepository) EXPECT() *MockClusterRepository_Expecter {
	return &MockClusterRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cluster, creds
func (_m *MockClusterRepository) Create(ctx context.Context, cluster *models.K8sCluster, creds *models.K8sClusterCredentials) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, cluster, creds)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) (*models.K8sCluster, error)); ok {
		return rf(ctx, cluster, creds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) *models.K8sCluster); ok {
		r0 = rf(ctx, cluster, creds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) error); ok {
		r1 = rf(ctx, cluster, creds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClusterRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster *models.K8sCluster
//   - creds *models.K8sClusterCredentials
func (_e *MockClusterRepository_Expecter) Create(ctx interface{}, cluster interface{}, creds interface{}) *MockClusterRepository_Create_Call {
	return &MockClusterRepository_Create_Call{Call: _e.mock.On("Create", ctx, cluster, creds)}
}

func (_c *MockClusterRepository_Create_Call) Run(run func(ctx context.Context, cluster *models.K8sCluster, creds *models.K8sClusterCredentials)) *MockClusterRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.K8sCluster), args[2].(*models.K8sClusterCredentials))
	})
	return _c
}

func (_c *MockClusterRepository_Create_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_Create_Call) RunAndReturn(run func(context.Context, *models.K8sCluster, *models.K8sClusterCredentials) (*models.K8sCluster, error)) *MockClusterRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockClusterRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClusterRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClusterRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockClusterRepository_Delete_Call {
	return &MockClusterRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockClusterRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockClusterRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterRepository_Delete_Call) Return(_a0 error) *MockClusterRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockClusterRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockClusterRepository) GetByID(ctx context.Context, id string) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.K8sCluster, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.K8sCluster); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClusterRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClusterRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockClusterRepository_GetByID_Call {
	return &MockClusterRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockClusterRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockClusterRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterRepository_GetByID_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.K8sCluster, error)) *MockClusterRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentials provides a mock function with given fields: ctx, id
func (_m *MockClusterRepository) GetCredentials(ctx context.Context, id string) (*models.K8sClusterCredentials, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentials")
	}

	var r0 *models.K8sClusterCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.K8sClusterCredentials, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.K8sClusterCredentials); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sClusterCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_GetCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentials'
type MockClusterRepository_GetCredentials_Call struct {
	*mock.Call
}

// GetCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClusterRepository_Expecter) GetCredentials(ctx interface{}, id interface{}) *MockClusterRepository_GetCredentials_Call {
	return &MockClusterRepository_GetCredentials_Call{Call: _e.mock.On("GetCredentials", ctx, id)}
}

func (_c *MockClusterRepository_GetCredentials_Call) Run(run func(ctx context.Context, id string)) *MockClusterRepository_GetCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterRepository_GetCredentials_Call) Return(_a0 *models.K8sClusterCredentials, _a1 error) *MockClusterRepository_GetCredentials_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_GetCredentials_Call) RunAndReturn(run func(context.Context, string) (*models.K8sClusterCredentials, error)) *MockClusterRepository_GetCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefault provides a mock function with given fields: ctx, projectID, env
func (_m *MockClusterRepository) GetDefault(ctx context.Context, projectID string, env *models.Environment) (*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID, env)

	if len(ret) == 0 {
		panic("no return value specified for GetDefault")
	}

	var r0 *models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Environment) (*models.K8sCluster, error)); ok {
		return rf(ctx, projectID, env)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Environment) *models.K8sCluster); ok {
		r0 = rf(ctx, projectID, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.Environment) error); ok {
		r1 = rf(ctx, projectID, env)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_GetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefault'
type MockClusterRepository_GetDefault_Call struct {
	*mock.Call
}

// GetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - env *models.Environment
func (_e *MockClusterRepository_Expecter) GetDefault(ctx interface{}, projectID interface{}, env interface{}) *MockClusterRepository_GetDefault_Call {
	return &MockClusterRepository_GetDefault_Call{Call: _e.mock.On("GetDefault", ctx, projectID, env)}
}

func (_c *MockClusterRepository_GetDefault_Call) Run(run func(ctx context.Context, projectID string, env *models.Environment)) *MockClusterRepository_GetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.Environment))
	})
	return _c
}

func (_c *MockClusterRepository_GetDefault_Call) Return(_a0 *models.K8sCluster, _a1 error) *MockClusterRepository_GetDefault_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_GetDefault_Call) RunAndReturn(run func(context.Context, string, *models.Environment) (*models.K8sCluster, error)) *MockClusterRepository_GetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// ListByEnvironment provides a mock function with given fields: ctx, projectID, env
func (_m *MockClusterRepository) ListByEnvironment(ctx context.Context, projectID string, env models.Environment) ([]*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID, env)

	if len(ret) == 0 {
		panic("no return value specified for ListByEnvironment")
	}

	var r0 []*models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) ([]*models.K8sCluster, error)); ok {
		return rf(ctx, projectID, env)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Environment) []*models.K8sCluster); ok {
		r0 = rf(ctx, projectID, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Environment) error); ok {
		r1 = rf(ctx, projectID, env)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_ListByEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByEnvironment'
type MockClusterRepository_ListByEnvironment_Call struct {
	*mock.Call
}

// ListByEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - env models.Environment
func (_e *MockClusterRepository_Expecter) ListByEnvironment(ctx interface{}, projectID interface{}, env interface{}) *MockClusterRepository_ListByEnvironment_Call {
	return &MockClusterRepository_ListByEnvironment_Call{Call: _e.mock.On("ListByEnvironment", ctx, projectID, env)}
}

func (_c *MockClusterRepository_ListByEnvironment_Call) Run(run func(ctx context.Context, projectID string, env models.Environment)) *MockClusterRepository_ListByEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Environment))
	})
	return _c
}

func (_c *MockClusterRepository_ListByEnvironment_Call) Return(_a0 []*models.K8sCluster, _a1 error) *MockClusterRepository_ListByEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_ListByEnvironment_Call) RunAndReturn(run func(context.Context, string, models.Environment) ([]*models.K8sCluster, error)) *MockClusterRepository_ListByEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProject provides a mock function with given fields: ctx, projectID
func (_m *MockClusterRepository) ListByProject(ctx context.Context, projectID string) ([]*models.K8sCluster, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProject")
	}

	var r0 []*models.K8sCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.K8sCluster, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.K8sCluster); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.K8sCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClusterRepository_ListByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProject'
type MockClusterRepository_ListByProject_Call struct {
	*mock.Call
}

// ListByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
func (_e *MockClusterRepository_Expecter) ListByProject(ctx interface{}, projectID interface{}) *MockClusterRepository_ListByProject_Call {
	return &MockClusterRepository_ListByProject_Call{Call: _e.mock.On("ListByProject", ctx, projectID)}
}

func (_c *MockClusterRepository_ListByProject_Call) Run(run func(ctx context.Context, projectID string)) *MockClusterRepository_ListByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterRepository_ListByProject_Call) Return(_a0 []*models.K8sCluster, _a1 error) *MockClusterRepository_ListByProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClusterRepository_ListByProject_Call) RunAndReturn(run func(context.Context, string) ([]*models.K8sCluster, error)) *MockClusterRepository_ListByProject_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefault provides a mock function with given fields: ctx, id
func (_m *MockClusterRepository) SetDefault(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterRepository_SetDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefault'
type MockClusterRepository_SetDefault_Call struct {
	*mock.Call
}

// SetDefault is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockClusterRepository_Expecter) SetDefault(ctx interface{}, id interface{}) *MockClusterRepository_SetDefault_Call {
	return &MockClusterRepository_SetDefault_Call{Call: _e.mock.On("SetDefault", ctx, id)}
}

func (_c *MockClusterRepository_SetDefault_Call) Run(run func(ctx context.Context, id string)) *MockClusterRepository_SetDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClusterRepository_SetDefault_Call) Return(_a0 error) *MockClusterRepository_SetDefault_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterRepository_SetDefault_Call) RunAndReturn(run func(context.Context, string) error) *MockClusterRepository_SetDefault_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRunnerConfig provides a mock function with given fields: ctx, id, config
func (_m *MockClusterRepository) UpdateRunnerConfig(ctx context.Context, id string, config *models.RunnerConfig) error {
	ret := _m.Called(ctx, id, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRunnerConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.RunnerConfig) error); ok {
		r0 = rf(ctx, id, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterRepository_UpdateRunnerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRunnerConfig'
type MockClusterRepository_UpdateRunnerConfig_Call struct {
	*mock.Call
}

// UpdateRunnerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - config *models.RunnerConfig
func (_e *MockClusterRepository_Expecter) UpdateRunnerConfig(ctx interface{}, id interface{}, config interface{}) *MockClusterRepository_UpdateRunnerConfig_Call {
	return &MockClusterRepository_UpdateRunnerConfig_Call{Call: _e.mock.On("UpdateRunnerConfig", ctx, id, config)}
}

func (_c *MockClusterRepository_UpdateRunnerConfig_Call) Run(run func(ctx context.Context, id string, config *models.RunnerConfig)) *MockClusterRepository_UpdateRunnerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.RunnerConfig))
	})
	return _c
}

func (_c *MockClusterRepository_UpdateRunnerConfig_Call) Return(_a0 error) *MockClusterRepository_UpdateRunnerConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterRepository_UpdateRunnerConfig_Call) RunAndReturn(run func(context.Context, string, *models.RunnerConfig) error) *MockClusterRepository_UpdateRunnerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, errorMsg
func (_m *MockClusterRepository) UpdateStatus(ctx context.Context, id string, status string, errorMsg *string) error {
	ret := _m.Called(ctx, id, status, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = rf(ctx, id, status, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockClusterRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
//   - errorMsg *string
func (_e *MockClusterRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, errorMsg interface{}) *MockClusterRepository_UpdateStatus_Call {
	return &MockClusterRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, errorMsg)}
}

func (_c *MockClusterRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status string, errorMsg *string)) *MockClusterRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockClusterRepository_UpdateStatus_Call) Return(_a0 error) *MockClusterRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string, *string) error) *MockClusterRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSutConfig provides a mock function with given fields: ctx, id, config
func (_m *MockClusterRepository) UpdateSutConfig(ctx context.Context, id string, config *models.SutConfig) error {
	ret := _m.Called(ctx, id, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSutConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SutConfig) error); ok {
		r0 = rf(ctx, id, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClusterRepository_UpdateSutConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSutConfig'
type MockClusterRepository_UpdateSutConfig_Call struct {
	*mock.Call
}

// UpdateSutConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - config *models.SutConfig
func (_e *MockClusterRepository_Expecter) UpdateSutConfig(ctx interface{}, id interface{}, config interface{}) *MockClusterRepository_UpdateSutConfig_Call {
	return &MockClusterRepository_UpdateSutConfig_Call{Call: _e.mock.On("UpdateSutConfig", ctx, id, config)}
}

func (_c *MockClusterRepository_UpdateSutConfig_Call) Run(run func(ctx context.Context, id string, config *models.SutConfig)) *MockClusterRepository_UpdateSutConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.SutConfig))
	})
	return _c
}

func (_c *MockClusterRepository_UpdateSutConfig_Call) Return(_a0 error) *MockClusterRepository_UpdateSutConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClusterRepository_UpdateSutConfig_Call) RunAndReturn(run func(context.Context, string, *models.SutConfig) error) *MockClusterRepository_UpdateSutConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClusterRepository creates a new instance of MockClusterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClusterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClusterRepository {
	mock := &MockClusterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
