// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	"github.com/MichielDean/ScaledTest/backend/internal/models"
)

// MockSettingsManager is an autogenerated mock type for the SettingsManager type
type MockSettingsManager struct {
	mock.Mock
}

type MockSettingsManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsManager) EXPECT() *MockSettingsManager_Expecter {
	return &MockSettingsManager_Expecter{mock: &_m.Mock}
}

// GetAuthSettings provides a mock function with given fields: ctx
func (_m *MockSettingsManager) GetAuthSettings(ctx context.Context) (*models.AuthSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthSettings")
	}

	var r0 *models.AuthSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.AuthSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.AuthSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_GetAuthSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthSettings'
type MockSettingsManager_GetAuthSettings_Call struct {
	*mock.Call
}

// GetAuthSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsManager_Expecter) GetAuthSettings(ctx interface{}) *MockSettingsManager_GetAuthSettings_Call {
	return &MockSettingsManager_GetAuthSettings_Call{Call: _e.mock.On("GetAuthSettings", ctx)}
}

func (_c *MockSettingsManager_GetAuthSettings_Call) Run(run func(ctx context.Context)) *MockSettingsManager_GetAuthSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSettingsManager_GetAuthSettings_Call) Return(_a0 *models.AuthSettings, _a1 error) *MockSettingsManager_GetAuthSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_GetAuthSettings_Call) RunAndReturn(run func(context.Context) (*models.AuthSettings, error)) *MockSettingsManager_GetAuthSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicConfig provides a mock function with given fields: ctx
func (_m *MockSettingsManager) GetPublicConfig(ctx context.Context) (*models.PublicConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicConfig")
	}

	var r0 *models.PublicConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.PublicConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.PublicConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PublicConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_GetPublicConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicConfig'
type MockSettingsManager_GetPublicConfig_Call struct {
	*mock.Call
}

// GetPublicConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsManager_Expecter) GetPublicConfig(ctx interface{}) *MockSettingsManager_GetPublicConfig_Call {
	return &MockSettingsManager_GetPublicConfig_Call{Call: _e.mock.On("GetPublicConfig", ctx)}
}

func (_c *MockSettingsManager_GetPublicConfig_Call) Run(run func(ctx context.Context)) *MockSettingsManager_GetPublicConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSettingsManager_GetPublicConfig_Call) Return(_a0 *models.PublicConfig, _a1 error) *MockSettingsManager_GetPublicConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_GetPublicConfig_Call) RunAndReturn(run func(context.Context) (*models.PublicConfig, error)) *MockSettingsManager_GetPublicConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function with given fields: ctx
func (_m *MockSettingsManager) GetSettings(ctx context.Context) (*models.SystemSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *models.SystemSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.SystemSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.SystemSettings); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SystemSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type MockSettingsManager_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsManager_Expecter) GetSettings(ctx interface{}) *MockSettingsManager_GetSettings_Call {
	return &MockSettingsManager_GetSettings_Call{Call: _e.mock.On("GetSettings", ctx)}
}

func (_c *MockSettingsManager_GetSettings_Call) Run(run func(ctx context.Context)) *MockSettingsManager_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSettingsManager_GetSettings_Call) Return(_a0 *models.SystemSettings, _a1 error) *MockSettingsManager_GetSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_GetSettings_Call) RunAndReturn(run func(context.Context) (*models.SystemSettings, error)) *MockSettingsManager_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: ctx
func (_m *MockSettingsManager) GetVersion(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockSettingsManager_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsManager_Expecter) GetVersion(ctx interface{}) *MockSettingsManager_GetVersion_Call {
	return &MockSettingsManager_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx)}
}

func (_c *MockSettingsManager_GetVersion_Call) Run(run func(ctx context.Context)) *MockSettingsManager_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSettingsManager_GetVersion_Call) Return(_a0 int, _a1 error) *MockSettingsManager_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_GetVersion_Call) RunAndReturn(run func(context.Context) (int, error)) *MockSettingsManager_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsAdminEmail provides a mock function with given fields: ctx, email
func (_m *MockSettingsManager) IsAdminEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for IsAdminEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_IsAdminEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdminEmail'
type MockSettingsManager_IsAdminEmail_Call struct {
	*mock.Call
}

// IsAdminEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockSettingsManager_Expecter) IsAdminEmail(ctx interface{}, email interface{}) *MockSettingsManager_IsAdminEmail_Call {
	return &MockSettingsManager_IsAdminEmail_Call{Call: _e.mock.On("IsAdminEmail", ctx, email)}
}

func (_c *MockSettingsManager_IsAdminEmail_Call) Run(run func(ctx context.Context, email string)) *MockSettingsManager_IsAdminEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSettingsManager_IsAdminEmail_Call) Return(_a0 bool, _a1 error) *MockSettingsManager_IsAdminEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_IsAdminEmail_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockSettingsManager_IsAdminEmail_Call {
	_c.Call.Return(run)
	return _c
}

// IsFirstUser provides a mock function with given fields: ctx
func (_m *MockSettingsManager) IsFirstUser(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsFirstUser")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_IsFirstUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFirstUser'
type MockSettingsManager_IsFirstUser_Call struct {
	*mock.Call
}

// IsFirstUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSettingsManager_Expecter) IsFirstUser(ctx interface{}) *MockSettingsManager_IsFirstUser_Call {
	return &MockSettingsManager_IsFirstUser_Call{Call: _e.mock.On("IsFirstUser", ctx)}
}

func (_c *MockSettingsManager_IsFirstUser_Call) Run(run func(ctx context.Context)) *MockSettingsManager_IsFirstUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSettingsManager_IsFirstUser_Call) Return(_a0 bool, _a1 error) *MockSettingsManager_IsFirstUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_IsFirstUser_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockSettingsManager_IsFirstUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function with given fields: ctx, req
func (_m *MockSettingsManager) UpdateSettings(ctx context.Context, req *models.UpdateSettingsRequest) (*models.SystemSettings, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 *models.SystemSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateSettingsRequest) (*models.SystemSettings, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateSettingsRequest) *models.SystemSettings); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SystemSettings)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateSettingsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsManager_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type MockSettingsManager_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateSettingsRequest
func (_e *MockSettingsManager_Expecter) UpdateSettings(ctx interface{}, req interface{}) *MockSettingsManager_UpdateSettings_Call {
	return &MockSettingsManager_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", ctx, req)}
}

func (_c *MockSettingsManager_UpdateSettings_Call) Run(run func(ctx context.Context, req *models.UpdateSettingsRequest)) *MockSettingsManager_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateSettingsRequest))
	})
	return _c
}

func (_c *MockSettingsManager_UpdateSettings_Call) Return(_a0 *models.SystemSettings, _a1 error) *MockSettingsManager_UpdateSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsManager_UpdateSettings_Call) RunAndReturn(run func(context.Context, *models.UpdateSettingsRequest) (*models.SystemSettings, error)) *MockSettingsManager_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSettingsManager creates a new instance of MockSettingsManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsManager {
	mock := &MockSettingsManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
