// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	mock "github.com/stretchr/testify/mock"
)

// MockUserManager is an autogenerated mock type for the UserManager type
type MockUserManager struct {
	mock.Mock
}

type MockUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManager) EXPECT() *MockUserManager_Expecter {
	return &MockUserManager_Expecter{mock: &_m.Mock}
}

// GetUserProfile provides a mock function with given fields: ctx, req
func (_m *MockUserManager) GetUserProfile(ctx context.Context, req *proto.GetUserProfileRequest) (*proto.UserProfileResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *proto.UserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetUserProfileRequest) (*proto.UserProfileResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetUserProfileRequest) *proto.UserProfileResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UserProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetUserProfileRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type MockUserManager_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - req *proto.GetUserProfileRequest
func (_e *MockUserManager_Expecter) GetUserProfile(ctx interface{}, req interface{}) *MockUserManager_GetUserProfile_Call {
	return &MockUserManager_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", ctx, req)}
}

func (_c *MockUserManager_GetUserProfile_Call) Run(run func(ctx context.Context, req *proto.GetUserProfileRequest)) *MockUserManager_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.GetUserProfileRequest))
	})
	return _c
}

func (_c *MockUserManager_GetUserProfile_Call) Return(_a0 *proto.UserProfileResponse, _a1 error) *MockUserManager_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_GetUserProfile_Call) RunAndReturn(run func(context.Context, *proto.GetUserProfileRequest) (*proto.UserProfileResponse, error)) *MockUserManager_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, req
func (_m *MockUserManager) ListUsers(ctx context.Context, req *proto.ListUsersRequest) (*proto.ListUsersResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *proto.ListUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListUsersRequest) (*proto.ListUsersResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListUsersRequest) *proto.ListUsersResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ListUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListUsersRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserManager_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - req *proto.ListUsersRequest
func (_e *MockUserManager_Expecter) ListUsers(ctx interface{}, req interface{}) *MockUserManager_ListUsers_Call {
	return &MockUserManager_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, req)}
}

func (_c *MockUserManager_ListUsers_Call) Run(run func(ctx context.Context, req *proto.ListUsersRequest)) *MockUserManager_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.ListUsersRequest))
	})
	return _c
}

func (_c *MockUserManager_ListUsers_Call) Return(_a0 *proto.ListUsersResponse, _a1 error) *MockUserManager_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_ListUsers_Call) RunAndReturn(run func(context.Context, *proto.ListUsersRequest) (*proto.ListUsersResponse, error)) *MockUserManager_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function with given fields: ctx, req
func (_m *MockUserManager) UpdateUserProfile(ctx context.Context, req *proto.UpdateUserProfileRequest) (*proto.UserProfileResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 *proto.UserProfileResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateUserProfileRequest) (*proto.UserProfileResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateUserProfileRequest) *proto.UserProfileResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UserProfileResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateUserProfileRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManager_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockUserManager_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - req *proto.UpdateUserProfileRequest
func (_e *MockUserManager_Expecter) UpdateUserProfile(ctx interface{}, req interface{}) *MockUserManager_UpdateUserProfile_Call {
	return &MockUserManager_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, req)}
}

func (_c *MockUserManager_UpdateUserProfile_Call) Run(run func(ctx context.Context, req *proto.UpdateUserProfileRequest)) *MockUserManager_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*proto.UpdateUserProfileRequest))
	})
	return _c
}

func (_c *MockUserManager_UpdateUserProfile_Call) Return(_a0 *proto.UserProfileResponse, _a1 error) *MockUserManager_UpdateUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManager_UpdateUserProfile_Call) RunAndReturn(run func(context.Context, *proto.UpdateUserProfileRequest) (*proto.UserProfileResponse, error)) *MockUserManager_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManager creates a new instance of MockUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManager {
	mock := &MockUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
