// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	k8s "github.com/MichielDean/ScaledTest/backend/internal/k8s"
	mock "github.com/stretchr/testify/mock"

	services "github.com/MichielDean/ScaledTest/backend/internal/services"
)

// MockTestExecutor is an autogenerated mock type for the TestExecutor type
type MockTestExecutor struct {
	mock.Mock
}

type MockTestExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestExecutor) EXPECT() *MockTestExecutor_Expecter {
	return &MockTestExecutor_Expecter{mock: &_m.Mock}
}

// CancelTestJob provides a mock function with given fields: ctx, jobID
func (_m *MockTestExecutor) CancelTestJob(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for CancelTestJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestExecutor_CancelTestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTestJob'
type MockTestExecutor_CancelTestJob_Call struct {
	*mock.Call
}

// CancelTestJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockTestExecutor_Expecter) CancelTestJob(ctx interface{}, jobID interface{}) *MockTestExecutor_CancelTestJob_Call {
	return &MockTestExecutor_CancelTestJob_Call{Call: _e.mock.On("CancelTestJob", ctx, jobID)}
}

func (_c *MockTestExecutor_CancelTestJob_Call) Run(run func(ctx context.Context, jobID string)) *MockTestExecutor_CancelTestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestExecutor_CancelTestJob_Call) Return(_a0 error) *MockTestExecutor_CancelTestJob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestExecutor_CancelTestJob_Call) RunAndReturn(run func(context.Context, string) error) *MockTestExecutor_CancelTestJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetK8sJobStatus provides a mock function with given fields: ctx, projectID, k8sJobName
func (_m *MockTestExecutor) GetK8sJobStatus(ctx context.Context, projectID string, k8sJobName string) (*services.K8sJobStatus, error) {
	ret := _m.Called(ctx, projectID, k8sJobName)

	if len(ret) == 0 {
		panic("no return value specified for GetK8sJobStatus")
	}

	var r0 *services.K8sJobStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*services.K8sJobStatus, error)); ok {
		return rf(ctx, projectID, k8sJobName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *services.K8sJobStatus); ok {
		r0 = rf(ctx, projectID, k8sJobName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.K8sJobStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, projectID, k8sJobName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestExecutor_GetK8sJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetK8sJobStatus'
type MockTestExecutor_GetK8sJobStatus_Call struct {
	*mock.Call
}

// GetK8sJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - k8sJobName string
func (_e *MockTestExecutor_Expecter) GetK8sJobStatus(ctx interface{}, projectID interface{}, k8sJobName interface{}) *MockTestExecutor_GetK8sJobStatus_Call {
	return &MockTestExecutor_GetK8sJobStatus_Call{Call: _e.mock.On("GetK8sJobStatus", ctx, projectID, k8sJobName)}
}

func (_c *MockTestExecutor_GetK8sJobStatus_Call) Run(run func(ctx context.Context, projectID string, k8sJobName string)) *MockTestExecutor_GetK8sJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTestExecutor_GetK8sJobStatus_Call) Return(_a0 *services.K8sJobStatus, _a1 error) *MockTestExecutor_GetK8sJobStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestExecutor_GetK8sJobStatus_Call) RunAndReturn(run func(context.Context, string, string) (*services.K8sJobStatus, error)) *MockTestExecutor_GetK8sJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestJob provides a mock function with given fields: ctx, jobID
func (_m *MockTestExecutor) GetTestJob(ctx context.Context, jobID string) (*services.TestJob, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestJob")
	}

	var r0 *services.TestJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.TestJob, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.TestJob); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.TestJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestExecutor_GetTestJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestJob'
type MockTestExecutor_GetTestJob_Call struct {
	*mock.Call
}

// GetTestJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *MockTestExecutor_Expecter) GetTestJob(ctx interface{}, jobID interface{}) *MockTestExecutor_GetTestJob_Call {
	return &MockTestExecutor_GetTestJob_Call{Call: _e.mock.On("GetTestJob", ctx, jobID)}
}

func (_c *MockTestExecutor_GetTestJob_Call) Run(run func(ctx context.Context, jobID string)) *MockTestExecutor_GetTestJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestExecutor_GetTestJob_Call) Return(_a0 *services.TestJob, _a1 error) *MockTestExecutor_GetTestJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestExecutor_GetTestJob_Call) RunAndReturn(run func(context.Context, string) (*services.TestJob, error)) *MockTestExecutor_GetTestJob_Call {
	_c.Call.Return(run)
	return _c
}

// ListTestJobs provides a mock function with given fields: ctx, projectID, page, pageSize, status, testImageID, k8sJobName
func (_m *MockTestExecutor) ListTestJobs(ctx context.Context, projectID string, page int32, pageSize int32, status *string, testImageID *string, k8sJobName *string) ([]*services.TestJob, int32, *services.JobStats, error) {
	ret := _m.Called(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)

	if len(ret) == 0 {
		panic("no return value specified for ListTestJobs")
	}

	var r0 []*services.TestJob
	var r1 int32
	var r2 *services.JobStats
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, *string, *string, *string) ([]*services.TestJob, int32, *services.JobStats, error)); ok {
		return rf(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, *string, *string, *string) []*services.TestJob); ok {
		r0 = rf(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.TestJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32, *string, *string, *string) int32); ok {
		r1 = rf(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, int32, *string, *string, *string) *services.JobStats); ok {
		r2 = rf(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*services.JobStats)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int32, int32, *string, *string, *string) error); ok {
		r3 = rf(ctx, projectID, page, pageSize, status, testImageID, k8sJobName)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTestExecutor_ListTestJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTestJobs'
type MockTestExecutor_ListTestJobs_Call struct {
	*mock.Call
}

// ListTestJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - page int32
//   - pageSize int32
//   - status *string
//   - testImageID *string
//   - k8sJobName *string
func (_e *MockTestExecutor_Expecter) ListTestJobs(ctx interface{}, projectID interface{}, page interface{}, pageSize interface{}, status interface{}, testImageID interface{}, k8sJobName interface{}) *MockTestExecutor_ListTestJobs_Call {
	return &MockTestExecutor_ListTestJobs_Call{Call: _e.mock.On("ListTestJobs", ctx, projectID, page, pageSize, status, testImageID, k8sJobName)}
}

func (_c *MockTestExecutor_ListTestJobs_Call) Run(run func(ctx context.Context, projectID string, page int32, pageSize int32, status *string, testImageID *string, k8sJobName *string)) *MockTestExecutor_ListTestJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(int32), args[4].(*string), args[5].(*string), args[6].(*string))
	})
	return _c
}

func (_c *MockTestExecutor_ListTestJobs_Call) Return(_a0 []*services.TestJob, _a1 int32, _a2 *services.JobStats, _a3 error) *MockTestExecutor_ListTestJobs_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockTestExecutor_ListTestJobs_Call) RunAndReturn(run func(context.Context, string, int32, int32, *string, *string, *string) ([]*services.TestJob, int32, *services.JobStats, error)) *MockTestExecutor_ListTestJobs_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerTestJobs provides a mock function with given fields: ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism
func (_m *MockTestExecutor) TriggerTestJobs(ctx context.Context, projectID string, testImageID string, userID string, testIDs []string, baseUrlOverride string, environment map[string]string, resources *k8s.ResourceRequirements, timeoutSeconds int32, parallelism int32) (string, string, []string, error) {
	ret := _m.Called(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)

	if len(ret) == 0 {
		panic("no return value specified for TriggerTestJobs")
	}

	var r0 string
	var r1 string
	var r2 []string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) (string, string, []string, error)); ok {
		return rf(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) string); ok {
		r0 = rf(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) string); ok {
		r1 = rf(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) []string); ok {
		r2 = rf(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]string)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) error); ok {
		r3 = rf(ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTestExecutor_TriggerTestJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerTestJobs'
type MockTestExecutor_TriggerTestJobs_Call struct {
	*mock.Call
}

// TriggerTestJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - testImageID string
//   - userID string
//   - testIDs []string
//   - baseUrlOverride string
//   - environment map[string]string
//   - resources *k8s.ResourceRequirements
//   - timeoutSeconds int32
//   - parallelism int32
func (_e *MockTestExecutor_Expecter) TriggerTestJobs(ctx interface{}, projectID interface{}, testImageID interface{}, userID interface{}, testIDs interface{}, baseUrlOverride interface{}, environment interface{}, resources interface{}, timeoutSeconds interface{}, parallelism interface{}) *MockTestExecutor_TriggerTestJobs_Call {
	return &MockTestExecutor_TriggerTestJobs_Call{Call: _e.mock.On("TriggerTestJobs", ctx, projectID, testImageID, userID, testIDs, baseUrlOverride, environment, resources, timeoutSeconds, parallelism)}
}

func (_c *MockTestExecutor_TriggerTestJobs_Call) Run(run func(ctx context.Context, projectID string, testImageID string, userID string, testIDs []string, baseUrlOverride string, environment map[string]string, resources *k8s.ResourceRequirements, timeoutSeconds int32, parallelism int32)) *MockTestExecutor_TriggerTestJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string), args[5].(string), args[6].(map[string]string), args[7].(*k8s.ResourceRequirements), args[8].(int32), args[9].(int32))
	})
	return _c
}

func (_c *MockTestExecutor_TriggerTestJobs_Call) Return(_a0 string, _a1 string, _a2 []string, _a3 error) *MockTestExecutor_TriggerTestJobs_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockTestExecutor_TriggerTestJobs_Call) RunAndReturn(run func(context.Context, string, string, string, []string, string, map[string]string, *k8s.ResourceRequirements, int32, int32) (string, string, []string, error)) *MockTestExecutor_TriggerTestJobs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobStatus provides a mock function with given fields: ctx, jobID, status, exitCode, podName
func (_m *MockTestExecutor) UpdateJobStatus(ctx context.Context, jobID string, status string, exitCode *int32, podName *string) error {
	ret := _m.Called(ctx, jobID, status, exitCode, podName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int32, *string) error); ok {
		r0 = rf(ctx, jobID, status, exitCode, podName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestExecutor_UpdateJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobStatus'
type MockTestExecutor_UpdateJobStatus_Call struct {
	*mock.Call
}

// UpdateJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - status string
//   - exitCode *int32
//   - podName *string
func (_e *MockTestExecutor_Expecter) UpdateJobStatus(ctx interface{}, jobID interface{}, status interface{}, exitCode interface{}, podName interface{}) *MockTestExecutor_UpdateJobStatus_Call {
	return &MockTestExecutor_UpdateJobStatus_Call{Call: _e.mock.On("UpdateJobStatus", ctx, jobID, status, exitCode, podName)}
}

func (_c *MockTestExecutor_UpdateJobStatus_Call) Run(run func(ctx context.Context, jobID string, status string, exitCode *int32, podName *string)) *MockTestExecutor_UpdateJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*int32), args[4].(*string))
	})
	return _c
}

func (_c *MockTestExecutor_UpdateJobStatus_Call) Return(_a0 error) *MockTestExecutor_UpdateJobStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestExecutor_UpdateJobStatus_Call) RunAndReturn(run func(context.Context, string, string, *int32, *string) error) *MockTestExecutor_UpdateJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestExecutor creates a new instance of MockTestExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestExecutor {
	mock := &MockTestExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
