// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/MichielDean/ScaledTest/backend/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// MockTestImageManager is an autogenerated mock type for the TestImageManager type
type MockTestImageManager struct {
	mock.Mock
}

type MockTestImageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestImageManager) EXPECT() *MockTestImageManager_Expecter {
	return &MockTestImageManager_Expecter{mock: &_m.Mock}
}

// AddTestImage provides a mock function with given fields: ctx, registryID, imagePath, imageTag, createdBy, projectID
func (_m *MockTestImageManager) AddTestImage(ctx context.Context, registryID string, imagePath string, imageTag string, createdBy string, projectID *string) (*services.TestImage, error) {
	ret := _m.Called(ctx, registryID, imagePath, imageTag, createdBy, projectID)

	if len(ret) == 0 {
		panic("no return value specified for AddTestImage")
	}

	var r0 *services.TestImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) (*services.TestImage, error)); ok {
		return rf(ctx, registryID, imagePath, imageTag, createdBy, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) *services.TestImage); ok {
		r0 = rf(ctx, registryID, imagePath, imageTag, createdBy, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.TestImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *string) error); ok {
		r1 = rf(ctx, registryID, imagePath, imageTag, createdBy, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestImageManager_AddTestImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTestImage'
type MockTestImageManager_AddTestImage_Call struct {
	*mock.Call
}

// AddTestImage is a helper method to define mock.On call
//   - ctx context.Context
//   - registryID string
//   - imagePath string
//   - imageTag string
//   - createdBy string
//   - projectID *string
func (_e *MockTestImageManager_Expecter) AddTestImage(ctx interface{}, registryID interface{}, imagePath interface{}, imageTag interface{}, createdBy interface{}, projectID interface{}) *MockTestImageManager_AddTestImage_Call {
	return &MockTestImageManager_AddTestImage_Call{Call: _e.mock.On("AddTestImage", ctx, registryID, imagePath, imageTag, createdBy, projectID)}
}

func (_c *MockTestImageManager_AddTestImage_Call) Run(run func(ctx context.Context, registryID string, imagePath string, imageTag string, createdBy string, projectID *string)) *MockTestImageManager_AddTestImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string))
	})
	return _c
}

func (_c *MockTestImageManager_AddTestImage_Call) Return(_a0 *services.TestImage, _a1 error) *MockTestImageManager_AddTestImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestImageManager_AddTestImage_Call) RunAndReturn(run func(context.Context, string, string, string, string, *string) (*services.TestImage, error)) *MockTestImageManager_AddTestImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTestImage provides a mock function with given fields: ctx, imageID
func (_m *MockTestImageManager) DeleteTestImage(ctx context.Context, imageID string) error {
	ret := _m.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTestImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestImageManager_DeleteTestImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTestImage'
type MockTestImageManager_DeleteTestImage_Call struct {
	*mock.Call
}

// DeleteTestImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockTestImageManager_Expecter) DeleteTestImage(ctx interface{}, imageID interface{}) *MockTestImageManager_DeleteTestImage_Call {
	return &MockTestImageManager_DeleteTestImage_Call{Call: _e.mock.On("DeleteTestImage", ctx, imageID)}
}

func (_c *MockTestImageManager_DeleteTestImage_Call) Run(run func(ctx context.Context, imageID string)) *MockTestImageManager_DeleteTestImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestImageManager_DeleteTestImage_Call) Return(_a0 error) *MockTestImageManager_DeleteTestImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestImageManager_DeleteTestImage_Call) RunAndReturn(run func(context.Context, string) error) *MockTestImageManager_DeleteTestImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestImage provides a mock function with given fields: ctx, imageID
func (_m *MockTestImageManager) GetTestImage(ctx context.Context, imageID string) (*services.TestImage, error) {
	ret := _m.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestImage")
	}

	var r0 *services.TestImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.TestImage, error)); ok {
		return rf(ctx, imageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.TestImage); ok {
		r0 = rf(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.TestImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestImageManager_GetTestImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestImage'
type MockTestImageManager_GetTestImage_Call struct {
	*mock.Call
}

// GetTestImage is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockTestImageManager_Expecter) GetTestImage(ctx interface{}, imageID interface{}) *MockTestImageManager_GetTestImage_Call {
	return &MockTestImageManager_GetTestImage_Call{Call: _e.mock.On("GetTestImage", ctx, imageID)}
}

func (_c *MockTestImageManager_GetTestImage_Call) Run(run func(ctx context.Context, imageID string)) *MockTestImageManager_GetTestImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTestImageManager_GetTestImage_Call) Return(_a0 *services.TestImage, _a1 error) *MockTestImageManager_GetTestImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTestImageManager_GetTestImage_Call) RunAndReturn(run func(context.Context, string) (*services.TestImage, error)) *MockTestImageManager_GetTestImage_Call {
	_c.Call.Return(run)
	return _c
}

// ListTestImages provides a mock function with given fields: ctx, userID, registryID, projectID, page, pageSize
func (_m *MockTestImageManager) ListTestImages(ctx context.Context, userID string, registryID *string, projectID *string, page int32, pageSize int32) ([]*services.TestImage, int32, error) {
	ret := _m.Called(ctx, userID, registryID, projectID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListTestImages")
	}

	var r0 []*services.TestImage
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) ([]*services.TestImage, int32, error)); ok {
		return rf(ctx, userID, registryID, projectID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) []*services.TestImage); ok {
		r0 = rf(ctx, userID, registryID, projectID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*services.TestImage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, int32, int32) int32); ok {
		r1 = rf(ctx, userID, registryID, projectID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *string, *string, int32, int32) error); ok {
		r2 = rf(ctx, userID, registryID, projectID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTestImageManager_ListTestImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTestImages'
type MockTestImageManager_ListTestImages_Call struct {
	*mock.Call
}

// ListTestImages is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - registryID *string
//   - projectID *string
//   - page int32
//   - pageSize int32
func (_e *MockTestImageManager_Expecter) ListTestImages(ctx interface{}, userID interface{}, registryID interface{}, projectID interface{}, page interface{}, pageSize interface{}) *MockTestImageManager_ListTestImages_Call {
	return &MockTestImageManager_ListTestImages_Call{Call: _e.mock.On("ListTestImages", ctx, userID, registryID, projectID, page, pageSize)}
}

func (_c *MockTestImageManager_ListTestImages_Call) Run(run func(ctx context.Context, userID string, registryID *string, projectID *string, page int32, pageSize int32)) *MockTestImageManager_ListTestImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string), args[4].(int32), args[5].(int32))
	})
	return _c
}

func (_c *MockTestImageManager_ListTestImages_Call) Return(_a0 []*services.TestImage, _a1 int32, _a2 error) *MockTestImageManager_ListTestImages_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTestImageManager_ListTestImages_Call) RunAndReturn(run func(context.Context, string, *string, *string, int32, int32) ([]*services.TestImage, int32, error)) *MockTestImageManager_ListTestImages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTestImageDiscovery provides a mock function with given fields: ctx, imageID, discoveredTests, framework, frameworkVersion, imageDigest
func (_m *MockTestImageManager) UpdateTestImageDiscovery(ctx context.Context, imageID string, discoveredTests []map[string]interface{}, framework *string, frameworkVersion *string, imageDigest *string) error {
	ret := _m.Called(ctx, imageID, discoveredTests, framework, frameworkVersion, imageDigest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestImageDiscovery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []map[string]interface{}, *string, *string, *string) error); ok {
		r0 = rf(ctx, imageID, discoveredTests, framework, frameworkVersion, imageDigest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestImageManager_UpdateTestImageDiscovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTestImageDiscovery'
type MockTestImageManager_UpdateTestImageDiscovery_Call struct {
	*mock.Call
}

// UpdateTestImageDiscovery is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
//   - discoveredTests []map[string]interface{}
//   - framework *string
//   - frameworkVersion *string
//   - imageDigest *string
func (_e *MockTestImageManager_Expecter) UpdateTestImageDiscovery(ctx interface{}, imageID interface{}, discoveredTests interface{}, framework interface{}, frameworkVersion interface{}, imageDigest interface{}) *MockTestImageManager_UpdateTestImageDiscovery_Call {
	return &MockTestImageManager_UpdateTestImageDiscovery_Call{Call: _e.mock.On("UpdateTestImageDiscovery", ctx, imageID, discoveredTests, framework, frameworkVersion, imageDigest)}
}

func (_c *MockTestImageManager_UpdateTestImageDiscovery_Call) Run(run func(ctx context.Context, imageID string, discoveredTests []map[string]interface{}, framework *string, frameworkVersion *string, imageDigest *string)) *MockTestImageManager_UpdateTestImageDiscovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]map[string]interface{}), args[3].(*string), args[4].(*string), args[5].(*string))
	})
	return _c
}

func (_c *MockTestImageManager_UpdateTestImageDiscovery_Call) Return(_a0 error) *MockTestImageManager_UpdateTestImageDiscovery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestImageManager_UpdateTestImageDiscovery_Call) RunAndReturn(run func(context.Context, string, []map[string]interface{}, *string, *string, *string) error) *MockTestImageManager_UpdateTestImageDiscovery_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTestImageDiscoveryStatus provides a mock function with given fields: ctx, imageID, status, errorMsg
func (_m *MockTestImageManager) UpdateTestImageDiscoveryStatus(ctx context.Context, imageID string, status string, errorMsg *string) error {
	ret := _m.Called(ctx, imageID, status, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestImageDiscoveryStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) error); ok {
		r0 = rf(ctx, imageID, status, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTestImageManager_UpdateTestImageDiscoveryStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTestImageDiscoveryStatus'
type MockTestImageManager_UpdateTestImageDiscoveryStatus_Call struct {
	*mock.Call
}

// UpdateTestImageDiscoveryStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
//   - status string
//   - errorMsg *string
func (_e *MockTestImageManager_Expecter) UpdateTestImageDiscoveryStatus(ctx interface{}, imageID interface{}, status interface{}, errorMsg interface{}) *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call {
	return &MockTestImageManager_UpdateTestImageDiscoveryStatus_Call{Call: _e.mock.On("UpdateTestImageDiscoveryStatus", ctx, imageID, status, errorMsg)}
}

func (_c *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call) Run(run func(ctx context.Context, imageID string, status string, errorMsg *string)) *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call) Return(_a0 error) *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call) RunAndReturn(run func(context.Context, string, string, *string) error) *MockTestImageManager_UpdateTestImageDiscoveryStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestImageManager creates a new instance of MockTestImageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestImageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestImageManager {
	mock := &MockTestImageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
