// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MichielDean/ScaledTest/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, project
func (_m *MockProjectRepository) Create(ctx context.Context, project *models.Project) (*models.Project, error) {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Project) (*models.Project, error)); ok {
		return rf(ctx, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Project) *models.Project); ok {
		r0 = rf(ctx, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Project) error); ok {
		r1 = rf(ctx, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - project *models.Project
func (_e *MockProjectRepository_Expecter) Create(ctx interface{}, project interface{}) *MockProjectRepository_Create_Call {
	return &MockProjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, project)}
}

func (_c *MockProjectRepository_Create_Call) Run(run func(ctx context.Context, project *models.Project)) *MockProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Create_Call) Return(_a0 *models.Project, _a1 error) *MockProjectRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Project) (*models.Project, error)) *MockProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(_a0 error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) GetByID(ctx context.Context, id string) (*models.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProjectRepository_GetByID_Call {
	return &MockProjectRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProjectRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockProjectRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) Return(_a0 *models.Project, _a1 error) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*models.Project, error)) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockProjectRepository) ListByUser(ctx context.Context, userID string, page int32, pageSize int32) ([]*models.Project, int32, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*models.Project
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]*models.Project, int32, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) []*models.Project); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) int32); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, int32) error); ok {
		r2 = rf(ctx, userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProjectRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockProjectRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int32
//   - pageSize int32
func (_e *MockProjectRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockProjectRepository_ListByUser_Call {
	return &MockProjectRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, page, pageSize)}
}

func (_c *MockProjectRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string, page int32, pageSize int32)) *MockProjectRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockProjectRepository_ListByUser_Call) Return(_a0 []*models.Project, _a1 int32, _a2 error) *MockProjectRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProjectRepository_ListByUser_Call) RunAndReturn(run func(context.Context, string, int32, int32) ([]*models.Project, int32, error)) *MockProjectRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, project
func (_m *MockProjectRepository) Update(ctx context.Context, project *models.Project) error {
	ret := _m.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Project) error); ok {
		r0 = rf(ctx, project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project *models.Project
func (_e *MockProjectRepository_Expecter) Update(ctx interface{}, project interface{}) *MockProjectRepository_Update_Call {
	return &MockProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, project)}
}

func (_c *MockProjectRepository_Update_Call) Run(run func(ctx context.Context, project *models.Project)) *MockProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Update_Call) Return(_a0 error) *MockProjectRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Project) error) *MockProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
