apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scaledtest

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - timescaledb.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
