services:
  # TimescaleDB with multiple databases: scaledtest (test results) and auth (Better Auth)
  postgres:
    image: timescale/timescaledb:2.14.2-pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: scaledtest
      POSTGRES_USER: scaledtest
      POSTGRES_PASSWORD: password
      # TimescaleDB specific settings
      POSTGRES_INITDB_ARGS: '--auth-host=md5 --auth-local=md5'
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
