// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "api.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceSignupProcedure is the fully-qualified name of the AuthService's Signup RPC.
	AuthServiceSignupProcedure = "/api.v1.AuthService/Signup"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/api.v1.AuthService/Login"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/api.v1.AuthService/Logout"
	// AuthServiceGetCurrentUserProcedure is the fully-qualified name of the AuthService's
	// GetCurrentUser RPC.
	AuthServiceGetCurrentUserProcedure = "/api.v1.AuthService/GetCurrentUser"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/api.v1.AuthService/RefreshToken"
)

// AuthServiceClient is a client for the api.v1.AuthService service.
type AuthServiceClient interface {
	// Signup creates a new user account
	Signup(context.Context, *connect.Request[proto.SignupRequest]) (*connect.Response[proto.AuthResponse], error)
	// Login authenticates a user and returns a JWT token
	Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.AuthResponse], error)
	// Logout invalidates the current session
	Logout(context.Context, *connect.Request[proto.LogoutRequest]) (*connect.Response[proto.LogoutResponse], error)
	// GetCurrentUser returns the currently authenticated user
	GetCurrentUser(context.Context, *connect.Request[proto.GetCurrentUserRequest]) (*connect.Response[proto.UserResponse], error)
	// RefreshToken refreshes an expired JWT token
	RefreshToken(context.Context, *connect.Request[proto.RefreshTokenRequest]) (*connect.Response[proto.AuthResponse], error)
}

// NewAuthServiceClient constructs a client for the api.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := proto.File_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		signup: connect.NewClient[proto.SignupRequest, proto.AuthResponse](
			httpClient,
			baseURL+AuthServiceSignupProcedure,
			connect.WithSchema(authServiceMethods.ByName("Signup")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[proto.LoginRequest, proto.AuthResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[proto.LogoutRequest, proto.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		getCurrentUser: connect.NewClient[proto.GetCurrentUserRequest, proto.UserResponse](
			httpClient,
			baseURL+AuthServiceGetCurrentUserProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[proto.RefreshTokenRequest, proto.AuthResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	signup         *connect.Client[proto.SignupRequest, proto.AuthResponse]
	login          *connect.Client[proto.LoginRequest, proto.AuthResponse]
	logout         *connect.Client[proto.LogoutRequest, proto.LogoutResponse]
	getCurrentUser *connect.Client[proto.GetCurrentUserRequest, proto.UserResponse]
	refreshToken   *connect.Client[proto.RefreshTokenRequest, proto.AuthResponse]
}

// Signup calls api.v1.AuthService.Signup.
func (c *authServiceClient) Signup(ctx context.Context, req *connect.Request[proto.SignupRequest]) (*connect.Response[proto.AuthResponse], error) {
	return c.signup.CallUnary(ctx, req)
}

// Login calls api.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[proto.LoginRequest]) (*connect.Response[proto.AuthResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Logout calls api.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[proto.LogoutRequest]) (*connect.Response[proto.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// GetCurrentUser calls api.v1.AuthService.GetCurrentUser.
func (c *authServiceClient) GetCurrentUser(ctx context.Context, req *connect.Request[proto.GetCurrentUserRequest]) (*connect.Response[proto.UserResponse], error) {
	return c.getCurrentUser.CallUnary(ctx, req)
}

// RefreshToken calls api.v1.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[proto.RefreshTokenRequest]) (*connect.Response[proto.AuthResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the api.v1.AuthService service.
type AuthServiceHandler interface {
	// Signup creates a new user account
	Signup(context.Context, *connect.Request[proto.SignupRequest]) (*connect.Response[proto.AuthResponse], error)
	// Login authenticates a user and returns a JWT token
	Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.AuthResponse], error)
	// Logout invalidates the current session
	Logout(context.Context, *connect.Request[proto.LogoutRequest]) (*connect.Response[proto.LogoutResponse], error)
	// GetCurrentUser returns the currently authenticated user
	GetCurrentUser(context.Context, *connect.Request[proto.GetCurrentUserRequest]) (*connect.Response[proto.UserResponse], error)
	// RefreshToken refreshes an expired JWT token
	RefreshToken(context.Context, *connect.Request[proto.RefreshTokenRequest]) (*connect.Response[proto.AuthResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := proto.File_auth_proto.Services().ByName("AuthService").Methods()
	authServiceSignupHandler := connect.NewUnaryHandler(
		AuthServiceSignupProcedure,
		svc.Signup,
		connect.WithSchema(authServiceMethods.ByName("Signup")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetCurrentUserHandler := connect.NewUnaryHandler(
		AuthServiceGetCurrentUserProcedure,
		svc.GetCurrentUser,
		connect.WithSchema(authServiceMethods.ByName("GetCurrentUser")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceSignupProcedure:
			authServiceSignupHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		case AuthServiceGetCurrentUserProcedure:
			authServiceGetCurrentUserHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Signup(context.Context, *connect.Request[proto.SignupRequest]) (*connect.Response[proto.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AuthService.Signup is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[proto.LoginRequest]) (*connect.Response[proto.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[proto.LogoutRequest]) (*connect.Response[proto.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AuthService.Logout is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetCurrentUser(context.Context, *connect.Request[proto.GetCurrentUserRequest]) (*connect.Response[proto.UserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AuthService.GetCurrentUser is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[proto.RefreshTokenRequest]) (*connect.Response[proto.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AuthService.RefreshToken is not implemented"))
}
