// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: health.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "api.v1.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceCheckProcedure is the fully-qualified name of the HealthService's Check RPC.
	HealthServiceCheckProcedure = "/api.v1.HealthService/Check"
	// HealthServiceReadyProcedure is the fully-qualified name of the HealthService's Ready RPC.
	HealthServiceReadyProcedure = "/api.v1.HealthService/Ready"
	// HealthServiceLiveProcedure is the fully-qualified name of the HealthService's Live RPC.
	HealthServiceLiveProcedure = "/api.v1.HealthService/Live"
	// HealthServiceWatchProcedure is the fully-qualified name of the HealthService's Watch RPC.
	HealthServiceWatchProcedure = "/api.v1.HealthService/Watch"
)

// HealthServiceClient is a client for the api.v1.HealthService service.
type HealthServiceClient interface {
	// Check performs a health check
	Check(context.Context, *connect.Request[proto.HealthCheckRequest]) (*connect.Response[proto.HealthCheckResponse], error)
	// Ready checks if the application is ready to serve traffic
	Ready(context.Context, *connect.Request[proto.ReadyRequest]) (*connect.Response[proto.ReadyResponse], error)
	// Live checks if the application is alive (for K8s liveness probes)
	Live(context.Context, *connect.Request[proto.LiveRequest]) (*connect.Response[proto.LiveResponse], error)
	// Watch streams health status changes
	Watch(context.Context, *connect.Request[proto.HealthCheckRequest]) (*connect.ServerStreamForClient[proto.HealthCheckResponse], error)
}

// NewHealthServiceClient constructs a client for the api.v1.HealthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := proto.File_health_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		check: connect.NewClient[proto.HealthCheckRequest, proto.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceCheckProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Check")),
			connect.WithClientOptions(opts...),
		),
		ready: connect.NewClient[proto.ReadyRequest, proto.ReadyResponse](
			httpClient,
			baseURL+HealthServiceReadyProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Ready")),
			connect.WithClientOptions(opts...),
		),
		live: connect.NewClient[proto.LiveRequest, proto.LiveResponse](
			httpClient,
			baseURL+HealthServiceLiveProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Live")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[proto.HealthCheckRequest, proto.HealthCheckResponse](
			httpClient,
			baseURL+HealthServiceWatchProcedure,
			connect.WithSchema(healthServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	check *connect.Client[proto.HealthCheckRequest, proto.HealthCheckResponse]
	ready *connect.Client[proto.ReadyRequest, proto.ReadyResponse]
	live  *connect.Client[proto.LiveRequest, proto.LiveResponse]
	watch *connect.Client[proto.HealthCheckRequest, proto.HealthCheckResponse]
}

// Check calls api.v1.HealthService.Check.
func (c *healthServiceClient) Check(ctx context.Context, req *connect.Request[proto.HealthCheckRequest]) (*connect.Response[proto.HealthCheckResponse], error) {
	return c.check.CallUnary(ctx, req)
}

// Ready calls api.v1.HealthService.Ready.
func (c *healthServiceClient) Ready(ctx context.Context, req *connect.Request[proto.ReadyRequest]) (*connect.Response[proto.ReadyResponse], error) {
	return c.ready.CallUnary(ctx, req)
}

// Live calls api.v1.HealthService.Live.
func (c *healthServiceClient) Live(ctx context.Context, req *connect.Request[proto.LiveRequest]) (*connect.Response[proto.LiveResponse], error) {
	return c.live.CallUnary(ctx, req)
}

// Watch calls api.v1.HealthService.Watch.
func (c *healthServiceClient) Watch(ctx context.Context, req *connect.Request[proto.HealthCheckRequest]) (*connect.ServerStreamForClient[proto.HealthCheckResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// HealthServiceHandler is an implementation of the api.v1.HealthService service.
type HealthServiceHandler interface {
	// Check performs a health check
	Check(context.Context, *connect.Request[proto.HealthCheckRequest]) (*connect.Response[proto.HealthCheckResponse], error)
	// Ready checks if the application is ready to serve traffic
	Ready(context.Context, *connect.Request[proto.ReadyRequest]) (*connect.Response[proto.ReadyResponse], error)
	// Live checks if the application is alive (for K8s liveness probes)
	Live(context.Context, *connect.Request[proto.LiveRequest]) (*connect.Response[proto.LiveResponse], error)
	// Watch streams health status changes
	Watch(context.Context, *connect.Request[proto.HealthCheckRequest], *connect.ServerStream[proto.HealthCheckResponse]) error
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := proto.File_health_proto.Services().ByName("HealthService").Methods()
	healthServiceCheckHandler := connect.NewUnaryHandler(
		HealthServiceCheckProcedure,
		svc.Check,
		connect.WithSchema(healthServiceMethods.ByName("Check")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceReadyHandler := connect.NewUnaryHandler(
		HealthServiceReadyProcedure,
		svc.Ready,
		connect.WithSchema(healthServiceMethods.ByName("Ready")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceLiveHandler := connect.NewUnaryHandler(
		HealthServiceLiveProcedure,
		svc.Live,
		connect.WithSchema(healthServiceMethods.ByName("Live")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceWatchHandler := connect.NewServerStreamHandler(
		HealthServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(healthServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceCheckProcedure:
			healthServiceCheckHandler.ServeHTTP(w, r)
		case HealthServiceReadyProcedure:
			healthServiceReadyHandler.ServeHTTP(w, r)
		case HealthServiceLiveProcedure:
			healthServiceLiveHandler.ServeHTTP(w, r)
		case HealthServiceWatchProcedure:
			healthServiceWatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) Check(context.Context, *connect.Request[proto.HealthCheckRequest]) (*connect.Response[proto.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HealthService.Check is not implemented"))
}

func (UnimplementedHealthServiceHandler) Ready(context.Context, *connect.Request[proto.ReadyRequest]) (*connect.Response[proto.ReadyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HealthService.Ready is not implemented"))
}

func (UnimplementedHealthServiceHandler) Live(context.Context, *connect.Request[proto.LiveRequest]) (*connect.Response[proto.LiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HealthService.Live is not implemented"))
}

func (UnimplementedHealthServiceHandler) Watch(context.Context, *connect.Request[proto.HealthCheckRequest], *connect.ServerStream[proto.HealthCheckResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.HealthService.Watch is not implemented"))
}
