// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: k8s_clusters.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// K8sClusterServiceName is the fully-qualified name of the K8sClusterService service.
	K8sClusterServiceName = "api.v1.K8sClusterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// K8SClusterServiceCreateClusterProcedure is the fully-qualified name of the K8sClusterService's
	// CreateCluster RPC.
	K8SClusterServiceCreateClusterProcedure = "/api.v1.K8sClusterService/CreateCluster"
	// K8SClusterServiceGetClusterProcedure is the fully-qualified name of the K8sClusterService's
	// GetCluster RPC.
	K8SClusterServiceGetClusterProcedure = "/api.v1.K8sClusterService/GetCluster"
	// K8SClusterServiceListClustersProcedure is the fully-qualified name of the K8sClusterService's
	// ListClusters RPC.
	K8SClusterServiceListClustersProcedure = "/api.v1.K8sClusterService/ListClusters"
	// K8SClusterServiceDeleteClusterProcedure is the fully-qualified name of the K8sClusterService's
	// DeleteCluster RPC.
	K8SClusterServiceDeleteClusterProcedure = "/api.v1.K8sClusterService/DeleteCluster"
	// K8SClusterServiceTestConnectionProcedure is the fully-qualified name of the K8sClusterService's
	// TestConnection RPC.
	K8SClusterServiceTestConnectionProcedure = "/api.v1.K8sClusterService/TestConnection"
	// K8SClusterServiceTestConnectionDirectProcedure is the fully-qualified name of the
	// K8sClusterService's TestConnectionDirect RPC.
	K8SClusterServiceTestConnectionDirectProcedure = "/api.v1.K8sClusterService/TestConnectionDirect"
	// K8SClusterServiceSetDefaultClusterProcedure is the fully-qualified name of the
	// K8sClusterService's SetDefaultCluster RPC.
	K8SClusterServiceSetDefaultClusterProcedure = "/api.v1.K8sClusterService/SetDefaultCluster"
	// K8SClusterServiceUpdateRunnerConfigProcedure is the fully-qualified name of the
	// K8sClusterService's UpdateRunnerConfig RPC.
	K8SClusterServiceUpdateRunnerConfigProcedure = "/api.v1.K8sClusterService/UpdateRunnerConfig"
	// K8SClusterServiceUpdateSutConfigProcedure is the fully-qualified name of the K8sClusterService's
	// UpdateSutConfig RPC.
	K8SClusterServiceUpdateSutConfigProcedure = "/api.v1.K8sClusterService/UpdateSutConfig"
)

// K8SClusterServiceClient is a client for the api.v1.K8sClusterService service.
type K8SClusterServiceClient interface {
	// CreateCluster adds a new Kubernetes cluster configuration
	CreateCluster(context.Context, *connect.Request[proto.CreateClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// GetCluster retrieves a specific cluster configuration
	GetCluster(context.Context, *connect.Request[proto.GetClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// ListClusters returns all clusters for a project
	ListClusters(context.Context, *connect.Request[proto.ListClustersRequest]) (*connect.Response[proto.ListClustersResponse], error)
	// DeleteCluster removes a cluster configuration
	DeleteCluster(context.Context, *connect.Request[proto.DeleteClusterRequest]) (*connect.Response[proto.DeleteClusterResponse], error)
	// TestConnection tests connectivity to a cluster
	TestConnection(context.Context, *connect.Request[proto.TestConnectionRequest]) (*connect.Response[proto.TestConnectionResponse], error)
	// TestConnectionDirect tests connectivity with provided credentials (no saved cluster)
	TestConnectionDirect(context.Context, *connect.Request[proto.TestConnectionDirectRequest]) (*connect.Response[proto.TestConnectionResponse], error)
	// SetDefaultCluster sets a cluster as the default for a project
	SetDefaultCluster(context.Context, *connect.Request[proto.SetDefaultClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// UpdateRunnerConfig updates the test runner configuration for a cluster
	UpdateRunnerConfig(context.Context, *connect.Request[proto.UpdateRunnerConfigRequest]) (*connect.Response[proto.ClusterResponse], error)
	// UpdateSutConfig updates the System Under Test configuration for a cluster
	UpdateSutConfig(context.Context, *connect.Request[proto.UpdateSutConfigRequest]) (*connect.Response[proto.ClusterResponse], error)
}

// NewK8SClusterServiceClient constructs a client for the api.v1.K8sClusterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewK8SClusterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) K8SClusterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	k8SClusterServiceMethods := proto.File_k8s_clusters_proto.Services().ByName("K8sClusterService").Methods()
	return &k8SClusterServiceClient{
		createCluster: connect.NewClient[proto.CreateClusterRequest, proto.ClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceCreateClusterProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("CreateCluster")),
			connect.WithClientOptions(opts...),
		),
		getCluster: connect.NewClient[proto.GetClusterRequest, proto.ClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceGetClusterProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("GetCluster")),
			connect.WithClientOptions(opts...),
		),
		listClusters: connect.NewClient[proto.ListClustersRequest, proto.ListClustersResponse](
			httpClient,
			baseURL+K8SClusterServiceListClustersProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("ListClusters")),
			connect.WithClientOptions(opts...),
		),
		deleteCluster: connect.NewClient[proto.DeleteClusterRequest, proto.DeleteClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceDeleteClusterProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("DeleteCluster")),
			connect.WithClientOptions(opts...),
		),
		testConnection: connect.NewClient[proto.TestConnectionRequest, proto.TestConnectionResponse](
			httpClient,
			baseURL+K8SClusterServiceTestConnectionProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("TestConnection")),
			connect.WithClientOptions(opts...),
		),
		testConnectionDirect: connect.NewClient[proto.TestConnectionDirectRequest, proto.TestConnectionResponse](
			httpClient,
			baseURL+K8SClusterServiceTestConnectionDirectProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("TestConnectionDirect")),
			connect.WithClientOptions(opts...),
		),
		setDefaultCluster: connect.NewClient[proto.SetDefaultClusterRequest, proto.ClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceSetDefaultClusterProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("SetDefaultCluster")),
			connect.WithClientOptions(opts...),
		),
		updateRunnerConfig: connect.NewClient[proto.UpdateRunnerConfigRequest, proto.ClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceUpdateRunnerConfigProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("UpdateRunnerConfig")),
			connect.WithClientOptions(opts...),
		),
		updateSutConfig: connect.NewClient[proto.UpdateSutConfigRequest, proto.ClusterResponse](
			httpClient,
			baseURL+K8SClusterServiceUpdateSutConfigProcedure,
			connect.WithSchema(k8SClusterServiceMethods.ByName("UpdateSutConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// k8SClusterServiceClient implements K8SClusterServiceClient.
type k8SClusterServiceClient struct {
	createCluster        *connect.Client[proto.CreateClusterRequest, proto.ClusterResponse]
	getCluster           *connect.Client[proto.GetClusterRequest, proto.ClusterResponse]
	listClusters         *connect.Client[proto.ListClustersRequest, proto.ListClustersResponse]
	deleteCluster        *connect.Client[proto.DeleteClusterRequest, proto.DeleteClusterResponse]
	testConnection       *connect.Client[proto.TestConnectionRequest, proto.TestConnectionResponse]
	testConnectionDirect *connect.Client[proto.TestConnectionDirectRequest, proto.TestConnectionResponse]
	setDefaultCluster    *connect.Client[proto.SetDefaultClusterRequest, proto.ClusterResponse]
	updateRunnerConfig   *connect.Client[proto.UpdateRunnerConfigRequest, proto.ClusterResponse]
	updateSutConfig      *connect.Client[proto.UpdateSutConfigRequest, proto.ClusterResponse]
}

// CreateCluster calls api.v1.K8sClusterService.CreateCluster.
func (c *k8SClusterServiceClient) CreateCluster(ctx context.Context, req *connect.Request[proto.CreateClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return c.createCluster.CallUnary(ctx, req)
}

// GetCluster calls api.v1.K8sClusterService.GetCluster.
func (c *k8SClusterServiceClient) GetCluster(ctx context.Context, req *connect.Request[proto.GetClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return c.getCluster.CallUnary(ctx, req)
}

// ListClusters calls api.v1.K8sClusterService.ListClusters.
func (c *k8SClusterServiceClient) ListClusters(ctx context.Context, req *connect.Request[proto.ListClustersRequest]) (*connect.Response[proto.ListClustersResponse], error) {
	return c.listClusters.CallUnary(ctx, req)
}

// DeleteCluster calls api.v1.K8sClusterService.DeleteCluster.
func (c *k8SClusterServiceClient) DeleteCluster(ctx context.Context, req *connect.Request[proto.DeleteClusterRequest]) (*connect.Response[proto.DeleteClusterResponse], error) {
	return c.deleteCluster.CallUnary(ctx, req)
}

// TestConnection calls api.v1.K8sClusterService.TestConnection.
func (c *k8SClusterServiceClient) TestConnection(ctx context.Context, req *connect.Request[proto.TestConnectionRequest]) (*connect.Response[proto.TestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// TestConnectionDirect calls api.v1.K8sClusterService.TestConnectionDirect.
func (c *k8SClusterServiceClient) TestConnectionDirect(ctx context.Context, req *connect.Request[proto.TestConnectionDirectRequest]) (*connect.Response[proto.TestConnectionResponse], error) {
	return c.testConnectionDirect.CallUnary(ctx, req)
}

// SetDefaultCluster calls api.v1.K8sClusterService.SetDefaultCluster.
func (c *k8SClusterServiceClient) SetDefaultCluster(ctx context.Context, req *connect.Request[proto.SetDefaultClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return c.setDefaultCluster.CallUnary(ctx, req)
}

// UpdateRunnerConfig calls api.v1.K8sClusterService.UpdateRunnerConfig.
func (c *k8SClusterServiceClient) UpdateRunnerConfig(ctx context.Context, req *connect.Request[proto.UpdateRunnerConfigRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return c.updateRunnerConfig.CallUnary(ctx, req)
}

// UpdateSutConfig calls api.v1.K8sClusterService.UpdateSutConfig.
func (c *k8SClusterServiceClient) UpdateSutConfig(ctx context.Context, req *connect.Request[proto.UpdateSutConfigRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return c.updateSutConfig.CallUnary(ctx, req)
}

// K8SClusterServiceHandler is an implementation of the api.v1.K8sClusterService service.
type K8SClusterServiceHandler interface {
	// CreateCluster adds a new Kubernetes cluster configuration
	CreateCluster(context.Context, *connect.Request[proto.CreateClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// GetCluster retrieves a specific cluster configuration
	GetCluster(context.Context, *connect.Request[proto.GetClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// ListClusters returns all clusters for a project
	ListClusters(context.Context, *connect.Request[proto.ListClustersRequest]) (*connect.Response[proto.ListClustersResponse], error)
	// DeleteCluster removes a cluster configuration
	DeleteCluster(context.Context, *connect.Request[proto.DeleteClusterRequest]) (*connect.Response[proto.DeleteClusterResponse], error)
	// TestConnection tests connectivity to a cluster
	TestConnection(context.Context, *connect.Request[proto.TestConnectionRequest]) (*connect.Response[proto.TestConnectionResponse], error)
	// TestConnectionDirect tests connectivity with provided credentials (no saved cluster)
	TestConnectionDirect(context.Context, *connect.Request[proto.TestConnectionDirectRequest]) (*connect.Response[proto.TestConnectionResponse], error)
	// SetDefaultCluster sets a cluster as the default for a project
	SetDefaultCluster(context.Context, *connect.Request[proto.SetDefaultClusterRequest]) (*connect.Response[proto.ClusterResponse], error)
	// UpdateRunnerConfig updates the test runner configuration for a cluster
	UpdateRunnerConfig(context.Context, *connect.Request[proto.UpdateRunnerConfigRequest]) (*connect.Response[proto.ClusterResponse], error)
	// UpdateSutConfig updates the System Under Test configuration for a cluster
	UpdateSutConfig(context.Context, *connect.Request[proto.UpdateSutConfigRequest]) (*connect.Response[proto.ClusterResponse], error)
}

// NewK8SClusterServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewK8SClusterServiceHandler(svc K8SClusterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	k8SClusterServiceMethods := proto.File_k8s_clusters_proto.Services().ByName("K8sClusterService").Methods()
	k8SClusterServiceCreateClusterHandler := connect.NewUnaryHandler(
		K8SClusterServiceCreateClusterProcedure,
		svc.CreateCluster,
		connect.WithSchema(k8SClusterServiceMethods.ByName("CreateCluster")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceGetClusterHandler := connect.NewUnaryHandler(
		K8SClusterServiceGetClusterProcedure,
		svc.GetCluster,
		connect.WithSchema(k8SClusterServiceMethods.ByName("GetCluster")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceListClustersHandler := connect.NewUnaryHandler(
		K8SClusterServiceListClustersProcedure,
		svc.ListClusters,
		connect.WithSchema(k8SClusterServiceMethods.ByName("ListClusters")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceDeleteClusterHandler := connect.NewUnaryHandler(
		K8SClusterServiceDeleteClusterProcedure,
		svc.DeleteCluster,
		connect.WithSchema(k8SClusterServiceMethods.ByName("DeleteCluster")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceTestConnectionHandler := connect.NewUnaryHandler(
		K8SClusterServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(k8SClusterServiceMethods.ByName("TestConnection")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceTestConnectionDirectHandler := connect.NewUnaryHandler(
		K8SClusterServiceTestConnectionDirectProcedure,
		svc.TestConnectionDirect,
		connect.WithSchema(k8SClusterServiceMethods.ByName("TestConnectionDirect")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceSetDefaultClusterHandler := connect.NewUnaryHandler(
		K8SClusterServiceSetDefaultClusterProcedure,
		svc.SetDefaultCluster,
		connect.WithSchema(k8SClusterServiceMethods.ByName("SetDefaultCluster")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceUpdateRunnerConfigHandler := connect.NewUnaryHandler(
		K8SClusterServiceUpdateRunnerConfigProcedure,
		svc.UpdateRunnerConfig,
		connect.WithSchema(k8SClusterServiceMethods.ByName("UpdateRunnerConfig")),
		connect.WithHandlerOptions(opts...),
	)
	k8SClusterServiceUpdateSutConfigHandler := connect.NewUnaryHandler(
		K8SClusterServiceUpdateSutConfigProcedure,
		svc.UpdateSutConfig,
		connect.WithSchema(k8SClusterServiceMethods.ByName("UpdateSutConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.K8sClusterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case K8SClusterServiceCreateClusterProcedure:
			k8SClusterServiceCreateClusterHandler.ServeHTTP(w, r)
		case K8SClusterServiceGetClusterProcedure:
			k8SClusterServiceGetClusterHandler.ServeHTTP(w, r)
		case K8SClusterServiceListClustersProcedure:
			k8SClusterServiceListClustersHandler.ServeHTTP(w, r)
		case K8SClusterServiceDeleteClusterProcedure:
			k8SClusterServiceDeleteClusterHandler.ServeHTTP(w, r)
		case K8SClusterServiceTestConnectionProcedure:
			k8SClusterServiceTestConnectionHandler.ServeHTTP(w, r)
		case K8SClusterServiceTestConnectionDirectProcedure:
			k8SClusterServiceTestConnectionDirectHandler.ServeHTTP(w, r)
		case K8SClusterServiceSetDefaultClusterProcedure:
			k8SClusterServiceSetDefaultClusterHandler.ServeHTTP(w, r)
		case K8SClusterServiceUpdateRunnerConfigProcedure:
			k8SClusterServiceUpdateRunnerConfigHandler.ServeHTTP(w, r)
		case K8SClusterServiceUpdateSutConfigProcedure:
			k8SClusterServiceUpdateSutConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedK8SClusterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedK8SClusterServiceHandler struct{}

func (UnimplementedK8SClusterServiceHandler) CreateCluster(context.Context, *connect.Request[proto.CreateClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.CreateCluster is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) GetCluster(context.Context, *connect.Request[proto.GetClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.GetCluster is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) ListClusters(context.Context, *connect.Request[proto.ListClustersRequest]) (*connect.Response[proto.ListClustersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.ListClusters is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) DeleteCluster(context.Context, *connect.Request[proto.DeleteClusterRequest]) (*connect.Response[proto.DeleteClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.DeleteCluster is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) TestConnection(context.Context, *connect.Request[proto.TestConnectionRequest]) (*connect.Response[proto.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.TestConnection is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) TestConnectionDirect(context.Context, *connect.Request[proto.TestConnectionDirectRequest]) (*connect.Response[proto.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.TestConnectionDirect is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) SetDefaultCluster(context.Context, *connect.Request[proto.SetDefaultClusterRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.SetDefaultCluster is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) UpdateRunnerConfig(context.Context, *connect.Request[proto.UpdateRunnerConfigRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.UpdateRunnerConfig is not implemented"))
}

func (UnimplementedK8SClusterServiceHandler) UpdateSutConfig(context.Context, *connect.Request[proto.UpdateSutConfigRequest]) (*connect.Response[proto.ClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.K8sClusterService.UpdateSutConfig is not implemented"))
}
