// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: test_jobs.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestJobServiceName is the fully-qualified name of the TestJobService service.
	TestJobServiceName = "api.v1.TestJobService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestJobServiceCreateProjectProcedure is the fully-qualified name of the TestJobService's
	// CreateProject RPC.
	TestJobServiceCreateProjectProcedure = "/api.v1.TestJobService/CreateProject"
	// TestJobServiceGetProjectProcedure is the fully-qualified name of the TestJobService's GetProject
	// RPC.
	TestJobServiceGetProjectProcedure = "/api.v1.TestJobService/GetProject"
	// TestJobServiceListProjectsProcedure is the fully-qualified name of the TestJobService's
	// ListProjects RPC.
	TestJobServiceListProjectsProcedure = "/api.v1.TestJobService/ListProjects"
	// TestJobServiceUpdateProjectProcedure is the fully-qualified name of the TestJobService's
	// UpdateProject RPC.
	TestJobServiceUpdateProjectProcedure = "/api.v1.TestJobService/UpdateProject"
	// TestJobServiceDeleteProjectProcedure is the fully-qualified name of the TestJobService's
	// DeleteProject RPC.
	TestJobServiceDeleteProjectProcedure = "/api.v1.TestJobService/DeleteProject"
	// TestJobServiceAddContainerRegistryProcedure is the fully-qualified name of the TestJobService's
	// AddContainerRegistry RPC.
	TestJobServiceAddContainerRegistryProcedure = "/api.v1.TestJobService/AddContainerRegistry"
	// TestJobServiceGetContainerRegistryProcedure is the fully-qualified name of the TestJobService's
	// GetContainerRegistry RPC.
	TestJobServiceGetContainerRegistryProcedure = "/api.v1.TestJobService/GetContainerRegistry"
	// TestJobServiceTestRegistryConnectionProcedure is the fully-qualified name of the TestJobService's
	// TestRegistryConnection RPC.
	TestJobServiceTestRegistryConnectionProcedure = "/api.v1.TestJobService/TestRegistryConnection"
	// TestJobServiceListContainerRegistriesProcedure is the fully-qualified name of the
	// TestJobService's ListContainerRegistries RPC.
	TestJobServiceListContainerRegistriesProcedure = "/api.v1.TestJobService/ListContainerRegistries"
	// TestJobServiceUpdateContainerRegistryProcedure is the fully-qualified name of the
	// TestJobService's UpdateContainerRegistry RPC.
	TestJobServiceUpdateContainerRegistryProcedure = "/api.v1.TestJobService/UpdateContainerRegistry"
	// TestJobServiceDeleteContainerRegistryProcedure is the fully-qualified name of the
	// TestJobService's DeleteContainerRegistry RPC.
	TestJobServiceDeleteContainerRegistryProcedure = "/api.v1.TestJobService/DeleteContainerRegistry"
	// TestJobServiceSyncRegistryImagesProcedure is the fully-qualified name of the TestJobService's
	// SyncRegistryImages RPC.
	TestJobServiceSyncRegistryImagesProcedure = "/api.v1.TestJobService/SyncRegistryImages"
	// TestJobServiceAddTestImageProcedure is the fully-qualified name of the TestJobService's
	// AddTestImage RPC.
	TestJobServiceAddTestImageProcedure = "/api.v1.TestJobService/AddTestImage"
	// TestJobServiceDiscoverTestsProcedure is the fully-qualified name of the TestJobService's
	// DiscoverTests RPC.
	TestJobServiceDiscoverTestsProcedure = "/api.v1.TestJobService/DiscoverTests"
	// TestJobServiceGetTestImageProcedure is the fully-qualified name of the TestJobService's
	// GetTestImage RPC.
	TestJobServiceGetTestImageProcedure = "/api.v1.TestJobService/GetTestImage"
	// TestJobServiceListTestImagesProcedure is the fully-qualified name of the TestJobService's
	// ListTestImages RPC.
	TestJobServiceListTestImagesProcedure = "/api.v1.TestJobService/ListTestImages"
	// TestJobServiceDeleteTestImageProcedure is the fully-qualified name of the TestJobService's
	// DeleteTestImage RPC.
	TestJobServiceDeleteTestImageProcedure = "/api.v1.TestJobService/DeleteTestImage"
	// TestJobServiceTriggerTestJobsProcedure is the fully-qualified name of the TestJobService's
	// TriggerTestJobs RPC.
	TestJobServiceTriggerTestJobsProcedure = "/api.v1.TestJobService/TriggerTestJobs"
	// TestJobServiceGetTestJobProcedure is the fully-qualified name of the TestJobService's GetTestJob
	// RPC.
	TestJobServiceGetTestJobProcedure = "/api.v1.TestJobService/GetTestJob"
	// TestJobServiceListTestJobsProcedure is the fully-qualified name of the TestJobService's
	// ListTestJobs RPC.
	TestJobServiceListTestJobsProcedure = "/api.v1.TestJobService/ListTestJobs"
	// TestJobServiceCancelTestJobProcedure is the fully-qualified name of the TestJobService's
	// CancelTestJob RPC.
	TestJobServiceCancelTestJobProcedure = "/api.v1.TestJobService/CancelTestJob"
	// TestJobServiceGetArtifactProcedure is the fully-qualified name of the TestJobService's
	// GetArtifact RPC.
	TestJobServiceGetArtifactProcedure = "/api.v1.TestJobService/GetArtifact"
	// TestJobServiceGetArtifactDownloadUrlProcedure is the fully-qualified name of the TestJobService's
	// GetArtifactDownloadUrl RPC.
	TestJobServiceGetArtifactDownloadUrlProcedure = "/api.v1.TestJobService/GetArtifactDownloadUrl"
	// TestJobServiceListArtifactsByTestRunProcedure is the fully-qualified name of the TestJobService's
	// ListArtifactsByTestRun RPC.
	TestJobServiceListArtifactsByTestRunProcedure = "/api.v1.TestJobService/ListArtifactsByTestRun"
)

// TestJobServiceClient is a client for the api.v1.TestJobService service.
type TestJobServiceClient interface {
	// Project Management
	CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[proto.GetProjectRequest]) (*connect.Response[proto.ProjectResponse], error)
	ListProjects(context.Context, *connect.Request[proto.ListProjectsRequest]) (*connect.Response[proto.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[proto.UpdateProjectRequest]) (*connect.Response[proto.ProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[proto.DeleteProjectRequest]) (*connect.Response[proto.DeleteProjectResponse], error)
	// Container Registry Management
	AddContainerRegistry(context.Context, *connect.Request[proto.AddContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	GetContainerRegistry(context.Context, *connect.Request[proto.GetContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	TestRegistryConnection(context.Context, *connect.Request[proto.TestRegistryConnectionRequest]) (*connect.Response[proto.TestRegistryConnectionResponse], error)
	ListContainerRegistries(context.Context, *connect.Request[proto.ListContainerRegistriesRequest]) (*connect.Response[proto.ListContainerRegistriesResponse], error)
	UpdateContainerRegistry(context.Context, *connect.Request[proto.UpdateContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	DeleteContainerRegistry(context.Context, *connect.Request[proto.DeleteContainerRegistryRequest]) (*connect.Response[proto.DeleteContainerRegistryResponse], error)
	SyncRegistryImages(context.Context, *connect.Request[proto.SyncRegistryImagesRequest]) (*connect.Response[proto.SyncRegistryImagesResponse], error)
	// Test Image Management
	AddTestImage(context.Context, *connect.Request[proto.AddTestImageRequest]) (*connect.Response[proto.TestImageResponse], error)
	DiscoverTests(context.Context, *connect.Request[proto.DiscoverTestsRequest]) (*connect.Response[proto.DiscoverTestsResponse], error)
	GetTestImage(context.Context, *connect.Request[proto.GetTestImageRequest]) (*connect.Response[proto.TestImageResponse], error)
	ListTestImages(context.Context, *connect.Request[proto.ListTestImagesRequest]) (*connect.Response[proto.ListTestImagesResponse], error)
	DeleteTestImage(context.Context, *connect.Request[proto.DeleteTestImageRequest]) (*connect.Response[proto.DeleteTestImageResponse], error)
	// Test Job Execution
	TriggerTestJobs(context.Context, *connect.Request[proto.TriggerTestJobsRequest]) (*connect.Response[proto.TriggerTestJobsResponse], error)
	GetTestJob(context.Context, *connect.Request[proto.GetTestJobRequest]) (*connect.Response[proto.TestJobResponse], error)
	ListTestJobs(context.Context, *connect.Request[proto.ListTestJobsRequest]) (*connect.Response[proto.ListTestJobsResponse], error)
	CancelTestJob(context.Context, *connect.Request[proto.CancelTestJobRequest]) (*connect.Response[proto.CancelTestJobResponse], error)
	// Artifact Management (read-only for now - upload implemented via separate service)
	GetArtifact(context.Context, *connect.Request[proto.GetArtifactRequest]) (*connect.Response[proto.ArtifactResponse], error)
	GetArtifactDownloadUrl(context.Context, *connect.Request[proto.GetArtifactDownloadUrlRequest]) (*connect.Response[proto.GetArtifactDownloadUrlResponse], error)
	ListArtifactsByTestRun(context.Context, *connect.Request[proto.ListArtifactsByTestRunRequest]) (*connect.Response[proto.ListArtifactsResponse], error)
}

// NewTestJobServiceClient constructs a client for the api.v1.TestJobService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestJobServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestJobServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testJobServiceMethods := proto.File_test_jobs_proto.Services().ByName("TestJobService").Methods()
	return &testJobServiceClient{
		createProject: connect.NewClient[proto.CreateProjectRequest, proto.CreateProjectResponse](
			httpClient,
			baseURL+TestJobServiceCreateProjectProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[proto.GetProjectRequest, proto.ProjectResponse](
			httpClient,
			baseURL+TestJobServiceGetProjectProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[proto.ListProjectsRequest, proto.ListProjectsResponse](
			httpClient,
			baseURL+TestJobServiceListProjectsProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[proto.UpdateProjectRequest, proto.ProjectResponse](
			httpClient,
			baseURL+TestJobServiceUpdateProjectProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[proto.DeleteProjectRequest, proto.DeleteProjectResponse](
			httpClient,
			baseURL+TestJobServiceDeleteProjectProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
		addContainerRegistry: connect.NewClient[proto.AddContainerRegistryRequest, proto.ContainerRegistryResponse](
			httpClient,
			baseURL+TestJobServiceAddContainerRegistryProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("AddContainerRegistry")),
			connect.WithClientOptions(opts...),
		),
		getContainerRegistry: connect.NewClient[proto.GetContainerRegistryRequest, proto.ContainerRegistryResponse](
			httpClient,
			baseURL+TestJobServiceGetContainerRegistryProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetContainerRegistry")),
			connect.WithClientOptions(opts...),
		),
		testRegistryConnection: connect.NewClient[proto.TestRegistryConnectionRequest, proto.TestRegistryConnectionResponse](
			httpClient,
			baseURL+TestJobServiceTestRegistryConnectionProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("TestRegistryConnection")),
			connect.WithClientOptions(opts...),
		),
		listContainerRegistries: connect.NewClient[proto.ListContainerRegistriesRequest, proto.ListContainerRegistriesResponse](
			httpClient,
			baseURL+TestJobServiceListContainerRegistriesProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("ListContainerRegistries")),
			connect.WithClientOptions(opts...),
		),
		updateContainerRegistry: connect.NewClient[proto.UpdateContainerRegistryRequest, proto.ContainerRegistryResponse](
			httpClient,
			baseURL+TestJobServiceUpdateContainerRegistryProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("UpdateContainerRegistry")),
			connect.WithClientOptions(opts...),
		),
		deleteContainerRegistry: connect.NewClient[proto.DeleteContainerRegistryRequest, proto.DeleteContainerRegistryResponse](
			httpClient,
			baseURL+TestJobServiceDeleteContainerRegistryProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("DeleteContainerRegistry")),
			connect.WithClientOptions(opts...),
		),
		syncRegistryImages: connect.NewClient[proto.SyncRegistryImagesRequest, proto.SyncRegistryImagesResponse](
			httpClient,
			baseURL+TestJobServiceSyncRegistryImagesProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("SyncRegistryImages")),
			connect.WithClientOptions(opts...),
		),
		addTestImage: connect.NewClient[proto.AddTestImageRequest, proto.TestImageResponse](
			httpClient,
			baseURL+TestJobServiceAddTestImageProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("AddTestImage")),
			connect.WithClientOptions(opts...),
		),
		discoverTests: connect.NewClient[proto.DiscoverTestsRequest, proto.DiscoverTestsResponse](
			httpClient,
			baseURL+TestJobServiceDiscoverTestsProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("DiscoverTests")),
			connect.WithClientOptions(opts...),
		),
		getTestImage: connect.NewClient[proto.GetTestImageRequest, proto.TestImageResponse](
			httpClient,
			baseURL+TestJobServiceGetTestImageProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetTestImage")),
			connect.WithClientOptions(opts...),
		),
		listTestImages: connect.NewClient[proto.ListTestImagesRequest, proto.ListTestImagesResponse](
			httpClient,
			baseURL+TestJobServiceListTestImagesProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("ListTestImages")),
			connect.WithClientOptions(opts...),
		),
		deleteTestImage: connect.NewClient[proto.DeleteTestImageRequest, proto.DeleteTestImageResponse](
			httpClient,
			baseURL+TestJobServiceDeleteTestImageProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("DeleteTestImage")),
			connect.WithClientOptions(opts...),
		),
		triggerTestJobs: connect.NewClient[proto.TriggerTestJobsRequest, proto.TriggerTestJobsResponse](
			httpClient,
			baseURL+TestJobServiceTriggerTestJobsProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("TriggerTestJobs")),
			connect.WithClientOptions(opts...),
		),
		getTestJob: connect.NewClient[proto.GetTestJobRequest, proto.TestJobResponse](
			httpClient,
			baseURL+TestJobServiceGetTestJobProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetTestJob")),
			connect.WithClientOptions(opts...),
		),
		listTestJobs: connect.NewClient[proto.ListTestJobsRequest, proto.ListTestJobsResponse](
			httpClient,
			baseURL+TestJobServiceListTestJobsProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("ListTestJobs")),
			connect.WithClientOptions(opts...),
		),
		cancelTestJob: connect.NewClient[proto.CancelTestJobRequest, proto.CancelTestJobResponse](
			httpClient,
			baseURL+TestJobServiceCancelTestJobProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("CancelTestJob")),
			connect.WithClientOptions(opts...),
		),
		getArtifact: connect.NewClient[proto.GetArtifactRequest, proto.ArtifactResponse](
			httpClient,
			baseURL+TestJobServiceGetArtifactProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetArtifact")),
			connect.WithClientOptions(opts...),
		),
		getArtifactDownloadUrl: connect.NewClient[proto.GetArtifactDownloadUrlRequest, proto.GetArtifactDownloadUrlResponse](
			httpClient,
			baseURL+TestJobServiceGetArtifactDownloadUrlProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("GetArtifactDownloadUrl")),
			connect.WithClientOptions(opts...),
		),
		listArtifactsByTestRun: connect.NewClient[proto.ListArtifactsByTestRunRequest, proto.ListArtifactsResponse](
			httpClient,
			baseURL+TestJobServiceListArtifactsByTestRunProcedure,
			connect.WithSchema(testJobServiceMethods.ByName("ListArtifactsByTestRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testJobServiceClient implements TestJobServiceClient.
type testJobServiceClient struct {
	createProject           *connect.Client[proto.CreateProjectRequest, proto.CreateProjectResponse]
	getProject              *connect.Client[proto.GetProjectRequest, proto.ProjectResponse]
	listProjects            *connect.Client[proto.ListProjectsRequest, proto.ListProjectsResponse]
	updateProject           *connect.Client[proto.UpdateProjectRequest, proto.ProjectResponse]
	deleteProject           *connect.Client[proto.DeleteProjectRequest, proto.DeleteProjectResponse]
	addContainerRegistry    *connect.Client[proto.AddContainerRegistryRequest, proto.ContainerRegistryResponse]
	getContainerRegistry    *connect.Client[proto.GetContainerRegistryRequest, proto.ContainerRegistryResponse]
	testRegistryConnection  *connect.Client[proto.TestRegistryConnectionRequest, proto.TestRegistryConnectionResponse]
	listContainerRegistries *connect.Client[proto.ListContainerRegistriesRequest, proto.ListContainerRegistriesResponse]
	updateContainerRegistry *connect.Client[proto.UpdateContainerRegistryRequest, proto.ContainerRegistryResponse]
	deleteContainerRegistry *connect.Client[proto.DeleteContainerRegistryRequest, proto.DeleteContainerRegistryResponse]
	syncRegistryImages      *connect.Client[proto.SyncRegistryImagesRequest, proto.SyncRegistryImagesResponse]
	addTestImage            *connect.Client[proto.AddTestImageRequest, proto.TestImageResponse]
	discoverTests           *connect.Client[proto.DiscoverTestsRequest, proto.DiscoverTestsResponse]
	getTestImage            *connect.Client[proto.GetTestImageRequest, proto.TestImageResponse]
	listTestImages          *connect.Client[proto.ListTestImagesRequest, proto.ListTestImagesResponse]
	deleteTestImage         *connect.Client[proto.DeleteTestImageRequest, proto.DeleteTestImageResponse]
	triggerTestJobs         *connect.Client[proto.TriggerTestJobsRequest, proto.TriggerTestJobsResponse]
	getTestJob              *connect.Client[proto.GetTestJobRequest, proto.TestJobResponse]
	listTestJobs            *connect.Client[proto.ListTestJobsRequest, proto.ListTestJobsResponse]
	cancelTestJob           *connect.Client[proto.CancelTestJobRequest, proto.CancelTestJobResponse]
	getArtifact             *connect.Client[proto.GetArtifactRequest, proto.ArtifactResponse]
	getArtifactDownloadUrl  *connect.Client[proto.GetArtifactDownloadUrlRequest, proto.GetArtifactDownloadUrlResponse]
	listArtifactsByTestRun  *connect.Client[proto.ListArtifactsByTestRunRequest, proto.ListArtifactsResponse]
}

// CreateProject calls api.v1.TestJobService.CreateProject.
func (c *testJobServiceClient) CreateProject(ctx context.Context, req *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// GetProject calls api.v1.TestJobService.GetProject.
func (c *testJobServiceClient) GetProject(ctx context.Context, req *connect.Request[proto.GetProjectRequest]) (*connect.Response[proto.ProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// ListProjects calls api.v1.TestJobService.ListProjects.
func (c *testJobServiceClient) ListProjects(ctx context.Context, req *connect.Request[proto.ListProjectsRequest]) (*connect.Response[proto.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// UpdateProject calls api.v1.TestJobService.UpdateProject.
func (c *testJobServiceClient) UpdateProject(ctx context.Context, req *connect.Request[proto.UpdateProjectRequest]) (*connect.Response[proto.ProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// DeleteProject calls api.v1.TestJobService.DeleteProject.
func (c *testJobServiceClient) DeleteProject(ctx context.Context, req *connect.Request[proto.DeleteProjectRequest]) (*connect.Response[proto.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// AddContainerRegistry calls api.v1.TestJobService.AddContainerRegistry.
func (c *testJobServiceClient) AddContainerRegistry(ctx context.Context, req *connect.Request[proto.AddContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return c.addContainerRegistry.CallUnary(ctx, req)
}

// GetContainerRegistry calls api.v1.TestJobService.GetContainerRegistry.
func (c *testJobServiceClient) GetContainerRegistry(ctx context.Context, req *connect.Request[proto.GetContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return c.getContainerRegistry.CallUnary(ctx, req)
}

// TestRegistryConnection calls api.v1.TestJobService.TestRegistryConnection.
func (c *testJobServiceClient) TestRegistryConnection(ctx context.Context, req *connect.Request[proto.TestRegistryConnectionRequest]) (*connect.Response[proto.TestRegistryConnectionResponse], error) {
	return c.testRegistryConnection.CallUnary(ctx, req)
}

// ListContainerRegistries calls api.v1.TestJobService.ListContainerRegistries.
func (c *testJobServiceClient) ListContainerRegistries(ctx context.Context, req *connect.Request[proto.ListContainerRegistriesRequest]) (*connect.Response[proto.ListContainerRegistriesResponse], error) {
	return c.listContainerRegistries.CallUnary(ctx, req)
}

// UpdateContainerRegistry calls api.v1.TestJobService.UpdateContainerRegistry.
func (c *testJobServiceClient) UpdateContainerRegistry(ctx context.Context, req *connect.Request[proto.UpdateContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return c.updateContainerRegistry.CallUnary(ctx, req)
}

// DeleteContainerRegistry calls api.v1.TestJobService.DeleteContainerRegistry.
func (c *testJobServiceClient) DeleteContainerRegistry(ctx context.Context, req *connect.Request[proto.DeleteContainerRegistryRequest]) (*connect.Response[proto.DeleteContainerRegistryResponse], error) {
	return c.deleteContainerRegistry.CallUnary(ctx, req)
}

// SyncRegistryImages calls api.v1.TestJobService.SyncRegistryImages.
func (c *testJobServiceClient) SyncRegistryImages(ctx context.Context, req *connect.Request[proto.SyncRegistryImagesRequest]) (*connect.Response[proto.SyncRegistryImagesResponse], error) {
	return c.syncRegistryImages.CallUnary(ctx, req)
}

// AddTestImage calls api.v1.TestJobService.AddTestImage.
func (c *testJobServiceClient) AddTestImage(ctx context.Context, req *connect.Request[proto.AddTestImageRequest]) (*connect.Response[proto.TestImageResponse], error) {
	return c.addTestImage.CallUnary(ctx, req)
}

// DiscoverTests calls api.v1.TestJobService.DiscoverTests.
func (c *testJobServiceClient) DiscoverTests(ctx context.Context, req *connect.Request[proto.DiscoverTestsRequest]) (*connect.Response[proto.DiscoverTestsResponse], error) {
	return c.discoverTests.CallUnary(ctx, req)
}

// GetTestImage calls api.v1.TestJobService.GetTestImage.
func (c *testJobServiceClient) GetTestImage(ctx context.Context, req *connect.Request[proto.GetTestImageRequest]) (*connect.Response[proto.TestImageResponse], error) {
	return c.getTestImage.CallUnary(ctx, req)
}

// ListTestImages calls api.v1.TestJobService.ListTestImages.
func (c *testJobServiceClient) ListTestImages(ctx context.Context, req *connect.Request[proto.ListTestImagesRequest]) (*connect.Response[proto.ListTestImagesResponse], error) {
	return c.listTestImages.CallUnary(ctx, req)
}

// DeleteTestImage calls api.v1.TestJobService.DeleteTestImage.
func (c *testJobServiceClient) DeleteTestImage(ctx context.Context, req *connect.Request[proto.DeleteTestImageRequest]) (*connect.Response[proto.DeleteTestImageResponse], error) {
	return c.deleteTestImage.CallUnary(ctx, req)
}

// TriggerTestJobs calls api.v1.TestJobService.TriggerTestJobs.
func (c *testJobServiceClient) TriggerTestJobs(ctx context.Context, req *connect.Request[proto.TriggerTestJobsRequest]) (*connect.Response[proto.TriggerTestJobsResponse], error) {
	return c.triggerTestJobs.CallUnary(ctx, req)
}

// GetTestJob calls api.v1.TestJobService.GetTestJob.
func (c *testJobServiceClient) GetTestJob(ctx context.Context, req *connect.Request[proto.GetTestJobRequest]) (*connect.Response[proto.TestJobResponse], error) {
	return c.getTestJob.CallUnary(ctx, req)
}

// ListTestJobs calls api.v1.TestJobService.ListTestJobs.
func (c *testJobServiceClient) ListTestJobs(ctx context.Context, req *connect.Request[proto.ListTestJobsRequest]) (*connect.Response[proto.ListTestJobsResponse], error) {
	return c.listTestJobs.CallUnary(ctx, req)
}

// CancelTestJob calls api.v1.TestJobService.CancelTestJob.
func (c *testJobServiceClient) CancelTestJob(ctx context.Context, req *connect.Request[proto.CancelTestJobRequest]) (*connect.Response[proto.CancelTestJobResponse], error) {
	return c.cancelTestJob.CallUnary(ctx, req)
}

// GetArtifact calls api.v1.TestJobService.GetArtifact.
func (c *testJobServiceClient) GetArtifact(ctx context.Context, req *connect.Request[proto.GetArtifactRequest]) (*connect.Response[proto.ArtifactResponse], error) {
	return c.getArtifact.CallUnary(ctx, req)
}

// GetArtifactDownloadUrl calls api.v1.TestJobService.GetArtifactDownloadUrl.
func (c *testJobServiceClient) GetArtifactDownloadUrl(ctx context.Context, req *connect.Request[proto.GetArtifactDownloadUrlRequest]) (*connect.Response[proto.GetArtifactDownloadUrlResponse], error) {
	return c.getArtifactDownloadUrl.CallUnary(ctx, req)
}

// ListArtifactsByTestRun calls api.v1.TestJobService.ListArtifactsByTestRun.
func (c *testJobServiceClient) ListArtifactsByTestRun(ctx context.Context, req *connect.Request[proto.ListArtifactsByTestRunRequest]) (*connect.Response[proto.ListArtifactsResponse], error) {
	return c.listArtifactsByTestRun.CallUnary(ctx, req)
}

// TestJobServiceHandler is an implementation of the api.v1.TestJobService service.
type TestJobServiceHandler interface {
	// Project Management
	CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.CreateProjectResponse], error)
	GetProject(context.Context, *connect.Request[proto.GetProjectRequest]) (*connect.Response[proto.ProjectResponse], error)
	ListProjects(context.Context, *connect.Request[proto.ListProjectsRequest]) (*connect.Response[proto.ListProjectsResponse], error)
	UpdateProject(context.Context, *connect.Request[proto.UpdateProjectRequest]) (*connect.Response[proto.ProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[proto.DeleteProjectRequest]) (*connect.Response[proto.DeleteProjectResponse], error)
	// Container Registry Management
	AddContainerRegistry(context.Context, *connect.Request[proto.AddContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	GetContainerRegistry(context.Context, *connect.Request[proto.GetContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	TestRegistryConnection(context.Context, *connect.Request[proto.TestRegistryConnectionRequest]) (*connect.Response[proto.TestRegistryConnectionResponse], error)
	ListContainerRegistries(context.Context, *connect.Request[proto.ListContainerRegistriesRequest]) (*connect.Response[proto.ListContainerRegistriesResponse], error)
	UpdateContainerRegistry(context.Context, *connect.Request[proto.UpdateContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error)
	DeleteContainerRegistry(context.Context, *connect.Request[proto.DeleteContainerRegistryRequest]) (*connect.Response[proto.DeleteContainerRegistryResponse], error)
	SyncRegistryImages(context.Context, *connect.Request[proto.SyncRegistryImagesRequest]) (*connect.Response[proto.SyncRegistryImagesResponse], error)
	// Test Image Management
	AddTestImage(context.Context, *connect.Request[proto.AddTestImageRequest]) (*connect.Response[proto.TestImageResponse], error)
	DiscoverTests(context.Context, *connect.Request[proto.DiscoverTestsRequest]) (*connect.Response[proto.DiscoverTestsResponse], error)
	GetTestImage(context.Context, *connect.Request[proto.GetTestImageRequest]) (*connect.Response[proto.TestImageResponse], error)
	ListTestImages(context.Context, *connect.Request[proto.ListTestImagesRequest]) (*connect.Response[proto.ListTestImagesResponse], error)
	DeleteTestImage(context.Context, *connect.Request[proto.DeleteTestImageRequest]) (*connect.Response[proto.DeleteTestImageResponse], error)
	// Test Job Execution
	TriggerTestJobs(context.Context, *connect.Request[proto.TriggerTestJobsRequest]) (*connect.Response[proto.TriggerTestJobsResponse], error)
	GetTestJob(context.Context, *connect.Request[proto.GetTestJobRequest]) (*connect.Response[proto.TestJobResponse], error)
	ListTestJobs(context.Context, *connect.Request[proto.ListTestJobsRequest]) (*connect.Response[proto.ListTestJobsResponse], error)
	CancelTestJob(context.Context, *connect.Request[proto.CancelTestJobRequest]) (*connect.Response[proto.CancelTestJobResponse], error)
	// Artifact Management (read-only for now - upload implemented via separate service)
	GetArtifact(context.Context, *connect.Request[proto.GetArtifactRequest]) (*connect.Response[proto.ArtifactResponse], error)
	GetArtifactDownloadUrl(context.Context, *connect.Request[proto.GetArtifactDownloadUrlRequest]) (*connect.Response[proto.GetArtifactDownloadUrlResponse], error)
	ListArtifactsByTestRun(context.Context, *connect.Request[proto.ListArtifactsByTestRunRequest]) (*connect.Response[proto.ListArtifactsResponse], error)
}

// NewTestJobServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestJobServiceHandler(svc TestJobServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testJobServiceMethods := proto.File_test_jobs_proto.Services().ByName("TestJobService").Methods()
	testJobServiceCreateProjectHandler := connect.NewUnaryHandler(
		TestJobServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(testJobServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetProjectHandler := connect.NewUnaryHandler(
		TestJobServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(testJobServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceListProjectsHandler := connect.NewUnaryHandler(
		TestJobServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(testJobServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceUpdateProjectHandler := connect.NewUnaryHandler(
		TestJobServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(testJobServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceDeleteProjectHandler := connect.NewUnaryHandler(
		TestJobServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(testJobServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceAddContainerRegistryHandler := connect.NewUnaryHandler(
		TestJobServiceAddContainerRegistryProcedure,
		svc.AddContainerRegistry,
		connect.WithSchema(testJobServiceMethods.ByName("AddContainerRegistry")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetContainerRegistryHandler := connect.NewUnaryHandler(
		TestJobServiceGetContainerRegistryProcedure,
		svc.GetContainerRegistry,
		connect.WithSchema(testJobServiceMethods.ByName("GetContainerRegistry")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceTestRegistryConnectionHandler := connect.NewUnaryHandler(
		TestJobServiceTestRegistryConnectionProcedure,
		svc.TestRegistryConnection,
		connect.WithSchema(testJobServiceMethods.ByName("TestRegistryConnection")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceListContainerRegistriesHandler := connect.NewUnaryHandler(
		TestJobServiceListContainerRegistriesProcedure,
		svc.ListContainerRegistries,
		connect.WithSchema(testJobServiceMethods.ByName("ListContainerRegistries")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceUpdateContainerRegistryHandler := connect.NewUnaryHandler(
		TestJobServiceUpdateContainerRegistryProcedure,
		svc.UpdateContainerRegistry,
		connect.WithSchema(testJobServiceMethods.ByName("UpdateContainerRegistry")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceDeleteContainerRegistryHandler := connect.NewUnaryHandler(
		TestJobServiceDeleteContainerRegistryProcedure,
		svc.DeleteContainerRegistry,
		connect.WithSchema(testJobServiceMethods.ByName("DeleteContainerRegistry")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceSyncRegistryImagesHandler := connect.NewUnaryHandler(
		TestJobServiceSyncRegistryImagesProcedure,
		svc.SyncRegistryImages,
		connect.WithSchema(testJobServiceMethods.ByName("SyncRegistryImages")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceAddTestImageHandler := connect.NewUnaryHandler(
		TestJobServiceAddTestImageProcedure,
		svc.AddTestImage,
		connect.WithSchema(testJobServiceMethods.ByName("AddTestImage")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceDiscoverTestsHandler := connect.NewUnaryHandler(
		TestJobServiceDiscoverTestsProcedure,
		svc.DiscoverTests,
		connect.WithSchema(testJobServiceMethods.ByName("DiscoverTests")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetTestImageHandler := connect.NewUnaryHandler(
		TestJobServiceGetTestImageProcedure,
		svc.GetTestImage,
		connect.WithSchema(testJobServiceMethods.ByName("GetTestImage")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceListTestImagesHandler := connect.NewUnaryHandler(
		TestJobServiceListTestImagesProcedure,
		svc.ListTestImages,
		connect.WithSchema(testJobServiceMethods.ByName("ListTestImages")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceDeleteTestImageHandler := connect.NewUnaryHandler(
		TestJobServiceDeleteTestImageProcedure,
		svc.DeleteTestImage,
		connect.WithSchema(testJobServiceMethods.ByName("DeleteTestImage")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceTriggerTestJobsHandler := connect.NewUnaryHandler(
		TestJobServiceTriggerTestJobsProcedure,
		svc.TriggerTestJobs,
		connect.WithSchema(testJobServiceMethods.ByName("TriggerTestJobs")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetTestJobHandler := connect.NewUnaryHandler(
		TestJobServiceGetTestJobProcedure,
		svc.GetTestJob,
		connect.WithSchema(testJobServiceMethods.ByName("GetTestJob")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceListTestJobsHandler := connect.NewUnaryHandler(
		TestJobServiceListTestJobsProcedure,
		svc.ListTestJobs,
		connect.WithSchema(testJobServiceMethods.ByName("ListTestJobs")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceCancelTestJobHandler := connect.NewUnaryHandler(
		TestJobServiceCancelTestJobProcedure,
		svc.CancelTestJob,
		connect.WithSchema(testJobServiceMethods.ByName("CancelTestJob")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetArtifactHandler := connect.NewUnaryHandler(
		TestJobServiceGetArtifactProcedure,
		svc.GetArtifact,
		connect.WithSchema(testJobServiceMethods.ByName("GetArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceGetArtifactDownloadUrlHandler := connect.NewUnaryHandler(
		TestJobServiceGetArtifactDownloadUrlProcedure,
		svc.GetArtifactDownloadUrl,
		connect.WithSchema(testJobServiceMethods.ByName("GetArtifactDownloadUrl")),
		connect.WithHandlerOptions(opts...),
	)
	testJobServiceListArtifactsByTestRunHandler := connect.NewUnaryHandler(
		TestJobServiceListArtifactsByTestRunProcedure,
		svc.ListArtifactsByTestRun,
		connect.WithSchema(testJobServiceMethods.ByName("ListArtifactsByTestRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.TestJobService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestJobServiceCreateProjectProcedure:
			testJobServiceCreateProjectHandler.ServeHTTP(w, r)
		case TestJobServiceGetProjectProcedure:
			testJobServiceGetProjectHandler.ServeHTTP(w, r)
		case TestJobServiceListProjectsProcedure:
			testJobServiceListProjectsHandler.ServeHTTP(w, r)
		case TestJobServiceUpdateProjectProcedure:
			testJobServiceUpdateProjectHandler.ServeHTTP(w, r)
		case TestJobServiceDeleteProjectProcedure:
			testJobServiceDeleteProjectHandler.ServeHTTP(w, r)
		case TestJobServiceAddContainerRegistryProcedure:
			testJobServiceAddContainerRegistryHandler.ServeHTTP(w, r)
		case TestJobServiceGetContainerRegistryProcedure:
			testJobServiceGetContainerRegistryHandler.ServeHTTP(w, r)
		case TestJobServiceTestRegistryConnectionProcedure:
			testJobServiceTestRegistryConnectionHandler.ServeHTTP(w, r)
		case TestJobServiceListContainerRegistriesProcedure:
			testJobServiceListContainerRegistriesHandler.ServeHTTP(w, r)
		case TestJobServiceUpdateContainerRegistryProcedure:
			testJobServiceUpdateContainerRegistryHandler.ServeHTTP(w, r)
		case TestJobServiceDeleteContainerRegistryProcedure:
			testJobServiceDeleteContainerRegistryHandler.ServeHTTP(w, r)
		case TestJobServiceSyncRegistryImagesProcedure:
			testJobServiceSyncRegistryImagesHandler.ServeHTTP(w, r)
		case TestJobServiceAddTestImageProcedure:
			testJobServiceAddTestImageHandler.ServeHTTP(w, r)
		case TestJobServiceDiscoverTestsProcedure:
			testJobServiceDiscoverTestsHandler.ServeHTTP(w, r)
		case TestJobServiceGetTestImageProcedure:
			testJobServiceGetTestImageHandler.ServeHTTP(w, r)
		case TestJobServiceListTestImagesProcedure:
			testJobServiceListTestImagesHandler.ServeHTTP(w, r)
		case TestJobServiceDeleteTestImageProcedure:
			testJobServiceDeleteTestImageHandler.ServeHTTP(w, r)
		case TestJobServiceTriggerTestJobsProcedure:
			testJobServiceTriggerTestJobsHandler.ServeHTTP(w, r)
		case TestJobServiceGetTestJobProcedure:
			testJobServiceGetTestJobHandler.ServeHTTP(w, r)
		case TestJobServiceListTestJobsProcedure:
			testJobServiceListTestJobsHandler.ServeHTTP(w, r)
		case TestJobServiceCancelTestJobProcedure:
			testJobServiceCancelTestJobHandler.ServeHTTP(w, r)
		case TestJobServiceGetArtifactProcedure:
			testJobServiceGetArtifactHandler.ServeHTTP(w, r)
		case TestJobServiceGetArtifactDownloadUrlProcedure:
			testJobServiceGetArtifactDownloadUrlHandler.ServeHTTP(w, r)
		case TestJobServiceListArtifactsByTestRunProcedure:
			testJobServiceListArtifactsByTestRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestJobServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestJobServiceHandler struct{}

func (UnimplementedTestJobServiceHandler) CreateProject(context.Context, *connect.Request[proto.CreateProjectRequest]) (*connect.Response[proto.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.CreateProject is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetProject(context.Context, *connect.Request[proto.GetProjectRequest]) (*connect.Response[proto.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetProject is not implemented"))
}

func (UnimplementedTestJobServiceHandler) ListProjects(context.Context, *connect.Request[proto.ListProjectsRequest]) (*connect.Response[proto.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.ListProjects is not implemented"))
}

func (UnimplementedTestJobServiceHandler) UpdateProject(context.Context, *connect.Request[proto.UpdateProjectRequest]) (*connect.Response[proto.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.UpdateProject is not implemented"))
}

func (UnimplementedTestJobServiceHandler) DeleteProject(context.Context, *connect.Request[proto.DeleteProjectRequest]) (*connect.Response[proto.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.DeleteProject is not implemented"))
}

func (UnimplementedTestJobServiceHandler) AddContainerRegistry(context.Context, *connect.Request[proto.AddContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.AddContainerRegistry is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetContainerRegistry(context.Context, *connect.Request[proto.GetContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetContainerRegistry is not implemented"))
}

func (UnimplementedTestJobServiceHandler) TestRegistryConnection(context.Context, *connect.Request[proto.TestRegistryConnectionRequest]) (*connect.Response[proto.TestRegistryConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.TestRegistryConnection is not implemented"))
}

func (UnimplementedTestJobServiceHandler) ListContainerRegistries(context.Context, *connect.Request[proto.ListContainerRegistriesRequest]) (*connect.Response[proto.ListContainerRegistriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.ListContainerRegistries is not implemented"))
}

func (UnimplementedTestJobServiceHandler) UpdateContainerRegistry(context.Context, *connect.Request[proto.UpdateContainerRegistryRequest]) (*connect.Response[proto.ContainerRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.UpdateContainerRegistry is not implemented"))
}

func (UnimplementedTestJobServiceHandler) DeleteContainerRegistry(context.Context, *connect.Request[proto.DeleteContainerRegistryRequest]) (*connect.Response[proto.DeleteContainerRegistryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.DeleteContainerRegistry is not implemented"))
}

func (UnimplementedTestJobServiceHandler) SyncRegistryImages(context.Context, *connect.Request[proto.SyncRegistryImagesRequest]) (*connect.Response[proto.SyncRegistryImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.SyncRegistryImages is not implemented"))
}

func (UnimplementedTestJobServiceHandler) AddTestImage(context.Context, *connect.Request[proto.AddTestImageRequest]) (*connect.Response[proto.TestImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.AddTestImage is not implemented"))
}

func (UnimplementedTestJobServiceHandler) DiscoverTests(context.Context, *connect.Request[proto.DiscoverTestsRequest]) (*connect.Response[proto.DiscoverTestsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.DiscoverTests is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetTestImage(context.Context, *connect.Request[proto.GetTestImageRequest]) (*connect.Response[proto.TestImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetTestImage is not implemented"))
}

func (UnimplementedTestJobServiceHandler) ListTestImages(context.Context, *connect.Request[proto.ListTestImagesRequest]) (*connect.Response[proto.ListTestImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.ListTestImages is not implemented"))
}

func (UnimplementedTestJobServiceHandler) DeleteTestImage(context.Context, *connect.Request[proto.DeleteTestImageRequest]) (*connect.Response[proto.DeleteTestImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.DeleteTestImage is not implemented"))
}

func (UnimplementedTestJobServiceHandler) TriggerTestJobs(context.Context, *connect.Request[proto.TriggerTestJobsRequest]) (*connect.Response[proto.TriggerTestJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.TriggerTestJobs is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetTestJob(context.Context, *connect.Request[proto.GetTestJobRequest]) (*connect.Response[proto.TestJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetTestJob is not implemented"))
}

func (UnimplementedTestJobServiceHandler) ListTestJobs(context.Context, *connect.Request[proto.ListTestJobsRequest]) (*connect.Response[proto.ListTestJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.ListTestJobs is not implemented"))
}

func (UnimplementedTestJobServiceHandler) CancelTestJob(context.Context, *connect.Request[proto.CancelTestJobRequest]) (*connect.Response[proto.CancelTestJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.CancelTestJob is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetArtifact(context.Context, *connect.Request[proto.GetArtifactRequest]) (*connect.Response[proto.ArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetArtifact is not implemented"))
}

func (UnimplementedTestJobServiceHandler) GetArtifactDownloadUrl(context.Context, *connect.Request[proto.GetArtifactDownloadUrlRequest]) (*connect.Response[proto.GetArtifactDownloadUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.GetArtifactDownloadUrl is not implemented"))
}

func (UnimplementedTestJobServiceHandler) ListArtifactsByTestRun(context.Context, *connect.Request[proto.ListArtifactsByTestRunRequest]) (*connect.Response[proto.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.TestJobService.ListArtifactsByTestRun is not implemented"))
}
