// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/MichielDean/ScaledTest/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "api.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProfileProcedure is the fully-qualified name of the UserService's
	// GetUserProfile RPC.
	UserServiceGetUserProfileProcedure = "/api.v1.UserService/GetUserProfile"
	// UserServiceUpdateUserProfileProcedure is the fully-qualified name of the UserService's
	// UpdateUserProfile RPC.
	UserServiceUpdateUserProfileProcedure = "/api.v1.UserService/UpdateUserProfile"
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/api.v1.UserService/ListUsers"
)

// UserServiceClient is a client for the api.v1.UserService service.
type UserServiceClient interface {
	// Get user profile by ID
	GetUserProfile(context.Context, *connect.Request[proto.GetUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error)
	// Update user profile
	UpdateUserProfile(context.Context, *connect.Request[proto.UpdateUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error)
	// List users (admin only)
	ListUsers(context.Context, *connect.Request[proto.ListUsersRequest]) (*connect.Response[proto.ListUsersResponse], error)
}

// NewUserServiceClient constructs a client for the api.v1.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := proto.File_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getUserProfile: connect.NewClient[proto.GetUserProfileRequest, proto.UserProfileResponse](
			httpClient,
			baseURL+UserServiceGetUserProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUserProfile")),
			connect.WithClientOptions(opts...),
		),
		updateUserProfile: connect.NewClient[proto.UpdateUserProfileRequest, proto.UserProfileResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUserProfile")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[proto.ListUsersRequest, proto.ListUsersResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUserProfile    *connect.Client[proto.GetUserProfileRequest, proto.UserProfileResponse]
	updateUserProfile *connect.Client[proto.UpdateUserProfileRequest, proto.UserProfileResponse]
	listUsers         *connect.Client[proto.ListUsersRequest, proto.ListUsersResponse]
}

// GetUserProfile calls api.v1.UserService.GetUserProfile.
func (c *userServiceClient) GetUserProfile(ctx context.Context, req *connect.Request[proto.GetUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error) {
	return c.getUserProfile.CallUnary(ctx, req)
}

// UpdateUserProfile calls api.v1.UserService.UpdateUserProfile.
func (c *userServiceClient) UpdateUserProfile(ctx context.Context, req *connect.Request[proto.UpdateUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error) {
	return c.updateUserProfile.CallUnary(ctx, req)
}

// ListUsers calls api.v1.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[proto.ListUsersRequest]) (*connect.Response[proto.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the api.v1.UserService service.
type UserServiceHandler interface {
	// Get user profile by ID
	GetUserProfile(context.Context, *connect.Request[proto.GetUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error)
	// Update user profile
	UpdateUserProfile(context.Context, *connect.Request[proto.UpdateUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error)
	// List users (admin only)
	ListUsers(context.Context, *connect.Request[proto.ListUsersRequest]) (*connect.Response[proto.ListUsersResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := proto.File_user_proto.Services().ByName("UserService").Methods()
	userServiceGetUserProfileHandler := connect.NewUnaryHandler(
		UserServiceGetUserProfileProcedure,
		svc.GetUserProfile,
		connect.WithSchema(userServiceMethods.ByName("GetUserProfile")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserProfileHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProfileProcedure,
		svc.UpdateUserProfile,
		connect.WithSchema(userServiceMethods.ByName("UpdateUserProfile")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProfileProcedure:
			userServiceGetUserProfileHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProfileProcedure:
			userServiceUpdateUserProfileHandler.ServeHTTP(w, r)
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUserProfile(context.Context, *connect.Request[proto.GetUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.UserService.GetUserProfile is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUserProfile(context.Context, *connect.Request[proto.UpdateUserProfileRequest]) (*connect.Response[proto.UserProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.UserService.UpdateUserProfile is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[proto.ListUsersRequest]) (*connect.Response[proto.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.UserService.ListUsers is not implemented"))
}
