// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

import "time"

type CtrfSchemaJson struct {
	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// GeneratedBy corresponds to the JSON schema field "generatedBy".
	GeneratedBy *string `json:"generatedBy,omitempty" yaml:"generatedBy,omitempty" mapstructure:"generatedBy,omitempty"`

	// ReportFormat corresponds to the JSON schema field "reportFormat".
	ReportFormat CtrfSchemaJsonReportFormat `json:"reportFormat" yaml:"reportFormat" mapstructure:"reportFormat"`

	// ReportId corresponds to the JSON schema field "reportId".
	ReportId *string `json:"reportId,omitempty" yaml:"reportId,omitempty" mapstructure:"reportId,omitempty"`

	// Results corresponds to the JSON schema field "results".
	Results CtrfSchemaJsonResults `json:"results" yaml:"results" mapstructure:"results"`

	// SpecVersion corresponds to the JSON schema field "specVersion".
	SpecVersion string `json:"specVersion" yaml:"specVersion" mapstructure:"specVersion"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp *time.Time `json:"timestamp,omitempty" yaml:"timestamp,omitempty" mapstructure:"timestamp,omitempty"`
}

type CtrfSchemaJsonReportFormat string

const CtrfSchemaJsonReportFormatCTRF CtrfSchemaJsonReportFormat = "CTRF"

type CtrfSchemaJsonResults struct {
	// Environment corresponds to the JSON schema field "environment".
	Environment *CtrfSchemaJsonResultsEnvironment `json:"environment,omitempty" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary CtrfSchemaJsonResultsSummary `json:"summary" yaml:"summary" mapstructure:"summary"`

	// Tests corresponds to the JSON schema field "tests".
	Tests []CtrfSchemaJsonResultsTestsElem `json:"tests" yaml:"tests" mapstructure:"tests"`

	// Tool corresponds to the JSON schema field "tool".
	Tool CtrfSchemaJsonResultsTool `json:"tool" yaml:"tool" mapstructure:"tool"`
}

type CtrfSchemaJsonResultsEnvironment struct {
	// AppName corresponds to the JSON schema field "appName".
	AppName *string `json:"appName,omitempty" yaml:"appName,omitempty" mapstructure:"appName,omitempty"`

	// AppVersion corresponds to the JSON schema field "appVersion".
	AppVersion *string `json:"appVersion,omitempty" yaml:"appVersion,omitempty" mapstructure:"appVersion,omitempty"`

	// BranchName corresponds to the JSON schema field "branchName".
	BranchName *string `json:"branchName,omitempty" yaml:"branchName,omitempty" mapstructure:"branchName,omitempty"`

	// BuildId corresponds to the JSON schema field "buildId".
	BuildId *string `json:"buildId,omitempty" yaml:"buildId,omitempty" mapstructure:"buildId,omitempty"`

	// BuildName corresponds to the JSON schema field "buildName".
	BuildName *string `json:"buildName,omitempty" yaml:"buildName,omitempty" mapstructure:"buildName,omitempty"`

	// BuildNumber corresponds to the JSON schema field "buildNumber".
	// Modified to accept both int and string from different reporters
	BuildNumber *FlexibleInt `json:"buildNumber,omitempty" yaml:"buildNumber,omitempty" mapstructure:"buildNumber,omitempty"`

	// BuildUrl corresponds to the JSON schema field "buildUrl".
	BuildUrl *string `json:"buildUrl,omitempty" yaml:"buildUrl,omitempty" mapstructure:"buildUrl,omitempty"`

	// Commit corresponds to the JSON schema field "commit".
	Commit *string `json:"commit,omitempty" yaml:"commit,omitempty" mapstructure:"commit,omitempty"`

	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// OsPlatform corresponds to the JSON schema field "osPlatform".
	OsPlatform *string `json:"osPlatform,omitempty" yaml:"osPlatform,omitempty" mapstructure:"osPlatform,omitempty"`

	// OsRelease corresponds to the JSON schema field "osRelease".
	OsRelease *string `json:"osRelease,omitempty" yaml:"osRelease,omitempty" mapstructure:"osRelease,omitempty"`

	// OsVersion corresponds to the JSON schema field "osVersion".
	OsVersion *string `json:"osVersion,omitempty" yaml:"osVersion,omitempty" mapstructure:"osVersion,omitempty"`

	// ReportName corresponds to the JSON schema field "reportName".
	ReportName *string `json:"reportName,omitempty" yaml:"reportName,omitempty" mapstructure:"reportName,omitempty"`

	// RepositoryName corresponds to the JSON schema field "repositoryName".
	RepositoryName *string `json:"repositoryName,omitempty" yaml:"repositoryName,omitempty" mapstructure:"repositoryName,omitempty"`

	// RepositoryUrl corresponds to the JSON schema field "repositoryUrl".
	RepositoryUrl *string `json:"repositoryUrl,omitempty" yaml:"repositoryUrl,omitempty" mapstructure:"repositoryUrl,omitempty"`

	// TestEnvironment corresponds to the JSON schema field "testEnvironment".
	TestEnvironment *string `json:"testEnvironment,omitempty" yaml:"testEnvironment,omitempty" mapstructure:"testEnvironment,omitempty"`
}

type CtrfSchemaJsonResultsSummary struct {
	// Duration corresponds to the JSON schema field "duration".
	Duration *int `json:"duration,omitempty" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// Failed corresponds to the JSON schema field "failed".
	Failed int `json:"failed" yaml:"failed" mapstructure:"failed"`

	// Flaky corresponds to the JSON schema field "flaky".
	Flaky *int `json:"flaky,omitempty" yaml:"flaky,omitempty" mapstructure:"flaky,omitempty"`

	// Other corresponds to the JSON schema field "other".
	Other int `json:"other" yaml:"other" mapstructure:"other"`

	// Passed corresponds to the JSON schema field "passed".
	Passed int `json:"passed" yaml:"passed" mapstructure:"passed"`

	// Pending corresponds to the JSON schema field "pending".
	Pending int `json:"pending" yaml:"pending" mapstructure:"pending"`

	// Skipped corresponds to the JSON schema field "skipped".
	Skipped int `json:"skipped" yaml:"skipped" mapstructure:"skipped"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start" yaml:"start" mapstructure:"start"`

	// Stop corresponds to the JSON schema field "stop".
	Stop int `json:"stop" yaml:"stop" mapstructure:"stop"`

	// Suites corresponds to the JSON schema field "suites".
	Suites *int `json:"suites,omitempty" yaml:"suites,omitempty" mapstructure:"suites,omitempty"`

	// Tests corresponds to the JSON schema field "tests".
	Tests int `json:"tests" yaml:"tests" mapstructure:"tests"`
}

type CtrfSchemaJsonResultsTestsElem struct {
	// Ai corresponds to the JSON schema field "ai".
	Ai *string `json:"ai,omitempty" yaml:"ai,omitempty" mapstructure:"ai,omitempty"`

	// Browser corresponds to the JSON schema field "browser".
	Browser *string `json:"browser,omitempty" yaml:"browser,omitempty" mapstructure:"browser,omitempty"`

	// Device corresponds to the JSON schema field "device".
	Device *string `json:"device,omitempty" yaml:"device,omitempty" mapstructure:"device,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration int `json:"duration" yaml:"duration" mapstructure:"duration"`

	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// FilePath corresponds to the JSON schema field "filePath".
	FilePath *string `json:"filePath,omitempty" yaml:"filePath,omitempty" mapstructure:"filePath,omitempty"`

	// Flaky corresponds to the JSON schema field "flaky".
	Flaky *bool `json:"flaky,omitempty" yaml:"flaky,omitempty" mapstructure:"flaky,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Line corresponds to the JSON schema field "line".
	Line *int `json:"line,omitempty" yaml:"line,omitempty" mapstructure:"line,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// RawStatus corresponds to the JSON schema field "rawStatus".
	RawStatus *string `json:"rawStatus,omitempty" yaml:"rawStatus,omitempty" mapstructure:"rawStatus,omitempty"`

	// Retries corresponds to the JSON schema field "retries".
	Retries *int `json:"retries,omitempty" yaml:"retries,omitempty" mapstructure:"retries,omitempty"`

	// Screenshot corresponds to the JSON schema field "screenshot".
	Screenshot *string `json:"screenshot,omitempty" yaml:"screenshot,omitempty" mapstructure:"screenshot,omitempty"`

	// Snippet corresponds to the JSON schema field "snippet".
	Snippet *string `json:"snippet,omitempty" yaml:"snippet,omitempty" mapstructure:"snippet,omitempty"`

	// Start corresponds to the JSON schema field "start".
	Start *int `json:"start,omitempty" yaml:"start,omitempty" mapstructure:"start,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status CtrfSchemaJsonResultsTestsElemStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Stop corresponds to the JSON schema field "stop".
	Stop *int `json:"stop,omitempty" yaml:"stop,omitempty" mapstructure:"stop,omitempty"`

	// Suite corresponds to the JSON schema field "suite".
	// Modified to accept both string and []string from different reporters
	Suite FlexibleStringArray `json:"suite,omitempty" yaml:"suite,omitempty" mapstructure:"suite,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Trace corresponds to the JSON schema field "trace".
	Trace *string `json:"trace,omitempty" yaml:"trace,omitempty" mapstructure:"trace,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type CtrfSchemaJsonResultsTestsElemStatus string

const CtrfSchemaJsonResultsTestsElemStatusFailed CtrfSchemaJsonResultsTestsElemStatus = "failed"
const CtrfSchemaJsonResultsTestsElemStatusOther CtrfSchemaJsonResultsTestsElemStatus = "other"
const CtrfSchemaJsonResultsTestsElemStatusPassed CtrfSchemaJsonResultsTestsElemStatus = "passed"
const CtrfSchemaJsonResultsTestsElemStatusPending CtrfSchemaJsonResultsTestsElemStatus = "pending"
const CtrfSchemaJsonResultsTestsElemStatusSkipped CtrfSchemaJsonResultsTestsElemStatus = "skipped"

type CtrfSchemaJsonResultsTool struct {
	// Extra corresponds to the JSON schema field "extra".
	Extra map[string]interface{} `json:"extra,omitempty" yaml:"extra,omitempty" mapstructure:"extra,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Version corresponds to the JSON schema field "version".
	Version *string `json:"version,omitempty" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}
