{{- if .Values.minio.enabled }}
{{- if not .Values.minio.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scaledtest.fullname" . }}-minio
  labels:
    {{- include "scaledtest.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
data:
  root-user: {{ .Values.minio.auth.rootUser | default "scaledtest" | b64enc | quote }}
  root-password: {{ .Values.minio.auth.rootPassword | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
{{- end }}
