name: Pull Request Validation

# The following permissions are required for this workflow:
# - `contents: read` is needed to fetch repository contents for the build and test steps.
# - `pull-requests: write` is needed to update pull request statuses and post comments.
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # Required Better Auth configuration
      BETTER_AUTH_SECRET: test-secret-key-for-ci-environment-32-chars
      BETTER_AUTH_URL: http://localhost:3000
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_APP_BASE_URL: http://localhost:3000

      # Database configuration
      DATABASE_URL: postgresql://scaledtest:password@127.0.0.1:5432/auth
      TIMESCALE_DATABASE_URL: postgresql://scaledtest:password@127.0.0.1:5432/scaledtest

      # Test users
      TEST_API_USERNAME: maintainer@scaledtest.com
      TEST_API_PASSWORD: Maintainer123!

      # TimescaleDB configuration
      TIMESCALEDB_HOST: localhost
      TIMESCALEDB_PORT: 5432
      TIMESCALEDB_DATABASE: scaledtest
      TIMESCALEDB_USERNAME: scaledtest
      TIMESCALEDB_PASSWORD: password

      # Test environment configuration
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=postgres") pg_isready -U scaledtest -d auth; then
              echo "Postgres is ready!"; break;
            fi
            echo "Waiting for Postgres... ($i)"; sleep 2;
            if [ "$i" -eq 30 ]; then
              echo "Postgres did not become ready in time."; exit 1;
            fi
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci
      - name: Run database migrations
        run: npm run migrate
      - name: Run all tests
        run: npm run test
